### ISSUE TITLE
Bug en la animación del Konami Code

### ISSUE THREAD

**Issue by TheLokin** [midudev/la-velada-web-oficial#159]
Parece que hay un problema con el Konami Code. Cuando se ingresa el código (Arriba, arriba, abajo, abajo, izquierda, derecha, izquierda, derecha, B, A), la animación asociada no se completa y se interrumpe antes de tiempo.

**Comment by IGnacho12** [comment]
Qué estas diciendo??

**Comment by seobryn** [comment]
Es verdad la animación se corta, adjunto video de lo que dice @TheLokin 


https://github.com/midudev/la-velada-web-oficial/assets/3819912/47ef1521-771f-41d5-86ea-c7e5fef7c888
