### ISSUE TITLE
Uso del 100% del procesador por el Smoke

### ISSUE THREAD

**Issue by IGnacho12** [midudev/la-velada-web-oficial#160]
![image](https://github.com/midudev/la-velada-web-oficial/assets/147453109/a4f94834-d2b9-4733-b341-d086849b98f7)
![image](https://github.com/midudev/la-velada-web-oficial/assets/147453109/3ecd6cd6-ddd5-4dcd-88a7-1d7b50b9dfaf)

**Comment by midudev** [comment]
¿Puedes revisar cómo funciona ahora? Asegurándote que has cerrado todas las demás pestañas. ¡Gracias!

**Comment by seobryn** [comment]
Hola @midudev @IGnacho12  He hecho la misma prueba en mi compu y no pasa eso, quizás puede ser alguna extension o pagina que tienes abierta

**Comment by GFrancV** [comment]
Hola @midudev, he realizado las pruebas en mi computador con Windows 11 y tengo el mismo problema de rendimiento al tener en primer plano abierta la pagina de la velada.
![image](https://github.com/midudev/la-velada-web-oficial/assets/35277540/b69e91f0-64d5-49bb-b4ca-75feaef26083)

**Comment by elpiojo95** [comment]
Yo tengo `Usar la aceleración de gráficos cuando esté disponible` desactivada en chrome y la web va al 100% de uso de cpu y super lenta, si lo activo pasa a ir correctamente

**Comment by midudev** [comment]
¿Podéis probar otra vez?

**Comment by elpiojo95** [comment]
https://github.com/midudev/la-velada-web-oficial/assets/32590506/33d7c1f3-412d-44ef-a8c2-ddf9be42a7a0


Ahora sin GPU va lento pero no consume el 100%, la web se puede ver después de que cargue. Antes era imposible navegar

**Comment by ferserc1** [comment]
a veces la función requestAnimationFrame() no implementa sincronización con el refresco de pantalla, y renderiza a toda la velocidad que le permite. A lo mejor está generando 400 frames por segundo, aunque la pantalla te funcione a 60.

Por mi experiencia, depende de muchas cosas, sobre todo del navegador y del driver de la tarjeta gráfica. Se puede solucionar creando un temporizador para llamar a requestAnimationFrame de forma diferida, y de paso se podría hacer que renderize a una velocidad menor que la velocidad de pantalla. Para esta animación seguramente bastaría con tirar a 30 fps

**Comment by seobryn** [comment]
Estoy haciendo pruebas en mi Compu con windows, al parecer tiene que ver con la aceleración Gráfica, si desctivo la GPU va mal, pero si la activo va de 10 @midudev @elpiojo95
