### ISSUE TITLE
Debate sobre posible nuevos efectos con three.js

### ISSUE THREAD

**Issue by Naza2021** [midudev/la-velada-web-oficial#174]
Hola! Espero que se encuentren super bien, abro esta issue por que estuve trabajando en una PR para mejorar el performance del smoke y acabo de darme cuenta que hicieron un merge de una PR donde eliminaban completamente el uso de three.js lo cual me parece perfecto. Ya que si, tenia un costo impresionante, es cargar 500 kb de puro javascript. Mis felicitaciones al usuario que consigo el mismo efecto con puro CSS <3

Pero quiero aportarle algunos conocimientos a la comunidad que hasta el día de hoy, no sabia que era posible,  y es que gracias a Apis modernas como:
OffscreenCanvas:
https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas

y utilizando web workers, se pueden eliminar toda la carga de three.js! E desplegado en el siguiente enlace un ejemplo básico.
https://la-velada-web-oficial-eosin.vercel.app/

Lo continuo utilizando y sigo obteniendo estas increíbles métricas web!
![image](https://github.com/midudev/la-velada-web-oficial/assets/63243377/2d7060bb-c286-4c6d-b8e0-92b063ffa54b)
![image](https://github.com/midudev/la-velada-web-oficial/assets/63243377/ef1b3ccf-fe3c-4d94-8941-3f9e647aef35)

Pueden ver en mi fork, algunos commits que estuve haciendo, no hice cambios para producción, si no mas bien son pruebas de conceptos, e incluso llegue a compilar con Rollup un archivo ts por que no encontre la manera de que Astro me transpile un archivo typescript para luego montarlo en un worker jajaja

Lo comento por si surge otra idea, donde podamos realmente explotar las capacidades de three.js para crear efectos "wow" por asi decirlo, y que no nos sintamos limitados por el performance.

Dejo algunos artículos interesantes:
https://evilmartians.com/chronicles/faster-webgl-three-js-3d-graphics-with-offscreencanvas-and-web-workers
https://docs.astro.build/en/guides/integrations-guide/partytown/

Muchas gracias por leer y que tenga bonito día!

**Comment by Jascuas** [comment]
ohhhhhhhhh increible! gracias

**Comment by JhonRomero26** [comment]
Increible @Naza2021 ese conocimiento que compartes, buscaba algo como tu aporte para aprender efectos locochones con poco costo para implementar en mis proyectos. 😊
