### ISSUE TITLE
Petición sobre ubicación de control de tema + redes 

### ISSUE THREAD

**Issue by antmonsep** [midudev/la-velada-web-oficial#184]
Hola! me parece muy bonito estos controles 
![image](https://github.com/midudev/la-velada-web-oficial/assets/69049114/e5df4f3f-52a6-4003-b96a-54f6fd7b00fb)
como sea, no sería bueno tener estos controles visibles desde el primer momento en que entras a la web? no tener que hacer scroll hasta el final de la página poder usarlos?

De nuevo, quedo muy bonita! saludos

**Comment by JhonRomero26** [comment]
Hola antmonsep! 👋

Gracias por tu comentario. La página tiene como objetivo presentar el evento de forma clara y concisa, y no tanto en dar mucha interactividad al usuario para que pase horas tras una pantalla. Estoy de acuerdo con tu sugerencia, sería más conveniente tener una funcionalidad más visible y fácil de usar. Por eso, se la considerara para el sitio web principal, donde los usuarios podrán interactuar más con el proyecto y disfrutar de una mejor experiencia donde pasaran horas tras la pantalla. 😊

Espero haberte ayudado con mi poco conocimiento de diseñador y programador. Igual no digo que no se lo pueda hacer. Saludos. 🤙

**Comment by JaviQD** [comment]
Hola!!

Me parece súper genial la idea de mover los controles a la parte superior o una parte que el usuario pueda verlo desde que ingresa a la pagina.

Saludos
