### ISSUE TITLE
Cambiar las horas de la fecha de presentación

### ISSUE THREAD

**Issue by JaviQD** [midudev/la-velada-web-oficial#193]
Mi idea seria -> 

Cambiar las horas de la fecha de presentación y adecuarlas a cada zona local de cada persona, la cual ingrese y pueda ver la hora exacta, la cual él pueda entrar a la hora adecuada.

Saludos.

**Comment by midudev** [comment]
Eso ya está hecho. Deberías al entrar poder ver la fecha en tu zona horaria.
