### ISSUE TITLE
Mobile diseño desplazado

### ISSUE THREAD

**Issue by joelmh-112** [midudev/la-velada-web-oficial#211]
Lo que hace desplazar son la imagen de fondo (drawn-x) y el div con blur, que como minimo ocupan 400px, en algunos mobiles mas pequeños hace que se desplace.

![image](https://github.com/midudev/la-velada-web-oficial/assets/81626570/a23ce771-a483-4887-af4c-ab55676a9b59)

**Comment by codejoss** [comment]
Mismo error al visualizar desde la app Safari de iOs en un iPhone 8.

NOTA: El detalle de que se ven dos flechas duplicadas para subir al inicio de la página es porque se tomaron diversas capturas de pantalla y se unieron en una sola para que se pueda visualizar mejor el error.

![photo-output](https://github.com/midudev/la-velada-web-oficial/assets/33957284/a2ce489d-1946-49e5-a738-d4db38334669)
