### ISSUE TITLE
Problema de rendimiento al clicar "AGREGAR AL CALENDARIO"

### ISSUE THREAD

**Issue by alfredontt** [midudev/la-velada-web-oficial#252]
Al clicar en el botón de "AGREGAR AL CALENDARIO" hace un efecto un velo borroso para mostrar las opciones de los diferentes sistemas de agenda, esto provoca que el rendimiento del PC vaya cayendo de forma progresiva si lo mantienes abierto. Entiendo que es debido al esfuerzo del procesador gráfico al construir la animación de fondo con el efecto blur.

**Comment by joelmh-112** [comment]
Sii probablemente sea el hecho de un blur sobre el ruido que el ruido esta sobre la animación de atrás. A ver cómo lo podemos solucionar!!

**Comment by alfredontt** [comment]
Google Chrome Versión 122.0.6261.71 (Build oficial) (64 bits)

**Comment by atascg01** [comment]
Puedes subir un vídeo capturando la pantalla para que lo veamos? Yo no he podido reproducirlo
