### ISSUE TITLE
El script `postinstall` falla en Windows 11

### ISSUE THREAD

**Issue by marsidev** [midudev/la-velada-web-oficial#305]
# Pre-requisitos

- [x] Estoy corriendo la última versión.
- [x] He revisado si ya hay un issue creado con las mismas características.

# Comportamiento esperado

Lo esperado es que al ejecutar `pnpm i` en Windows, se instalen las dependencias sin error alguno.

# Comportamiento actual

![image](https://github.com/midudev/la-velada-web-oficial/assets/56328053/bcbf0d97-cbfd-4317-84eb-6c3f808593c6)

# Información del bug

Parece estar relacionado a este script (introducido en #178):

```json
"scripts": {
  "postinstall": "[ -d '.husky' ] && husky install || true"
}
```

## Pasos para reproducirlo

```bash
git clone https://github.com/midudev/la-velada-web-oficial
cd la-velada-web-oficial
pnpm i
```

## Contexto

- Sistema operativo: Windows 11, Powershell 7.4.1

**Comment by vurtune** [comment]
Hola, estás usando cygwin?

**Comment by marsidev** [comment]
> Hola, estás usando cygwin?

No, uso Powershell 7.4.1 en Windows Terminal con Oh My Posh

**Comment by vurtune** [comment]
> > Hola, estás usando cygwin?
> 
> No, uso Powershell 7.4.1 en Windows Terminal con Oh My Posh

Ya veo, tu shell (interpretador de comandos) no comprende la condición que te da el error.
[ -d '.husky' ] # si esta expresión es verdadera (encuentra el directorio .husky)
&& husky install # ejecuta esto
|| true # sino esto
Shells como bash o zsh interpretan bien esto.
Te recomiendo utilizar WSL 2 o simplemente modifica esa línea para tu sistema.

**Comment by marsidev** [comment]
Entiendo que es un problema de incompatibilidad. Pero el script `postinstall` tampoco es interpretado usando CMD, la básica consola por defecto en cualquier máquina Windows.

![image](https://github.com/midudev/la-velada-web-oficial/assets/56328053/31363f05-5fa1-44fb-93fa-197b53ebcbf5)

Sugiero cambiar el script para que sea compatible en cualquier entorno (Linux/macOS/Windows).

No hago el PR porque realmente no entiendo qué hace el script y no uso Husky.

**Comment by joelmh-112** [comment]
Yo estoy igual que tu @marsidev !! La cosa es que husky en windows pues funciona distinto. Por eso como dice @vurtune si te instalas alguna consola de comandos de linux (git bash por ejemplo) o te pones el wsl2 ya podras ejecutarlo sin problema como puedes ver en la imagen que adjunto.

![image](https://github.com/midudev/la-velada-web-oficial/assets/81626570/33deb481-d203-4dd4-a7c5-b809963ddd7a)

No se si habría alguna manera de hacer que ejecute una cosa u otra usando linux/macos o usando windows. A ver si alguien sabe como hacerlo. Igualmente es muy recomendable usar wsl2.

**Comment by marsidev** [comment]
Gracias por comentar muchachos, entiendo lo beneficioso que puede ser usar consolas de Linux como WSL, mas no comparto que se deba forzar a los usuarios usarlo solo para ejecutar un script de Husky. En todo caso, se tendría que actualizar el README para advertir esto, o bien arreglar el script `postinstall`.

**Comment by vurtune** [comment]
Funciona en Linux y Mac. Windows 🤪
Por eso y muchas otras cosas más crearon WSL, úsenlo como buena práctica, el problema es que es un Linux virtualizado, es decir no tendrá un rendimiento óptimo. Para sacarle provecho a Linux usar un dual boot con Windows o comprarse una Mac.
P.S. `scripts.postinstall` lo interpreta Node para ejecutarlo en tu terminal

**Comment by marsidev** [comment]
Gracias por tus sugerencias, @vurtune, aunque me parece que se está desviando el foco del issue.

Esta issue ya no tendrá sentido cuando se indique en el README que en Windows se debe instalar WSL obligatoriamente, o bien al corregir el script (de ser corregible).

Estuve [buscando](https://github.com/search?q=postinstall+husky+path%3A*package.json&type=code) en otros repos, y muchos simplemente usan `"postinstall": "husky install"`, podríamos usar este script? O tiene alguna desventaja sobre el actual?

**Comment by KROSF** [comment]
@marsidev prueba con mi pr #309 debería de funcionarte bien

**Comment by vurtune** [comment]
Es correcto, puedes usar ese comando siempre y cuando tengas instalado Husky, si no tienes husky remueve toda la línea, así de sencillo, pero como mencionaron, Husky tiene su proposito, sino puedes hacer su proposito manualmente o con otro comando.

**Comment by marsidev** [comment]
> marsidev prueba con mi pr #309 debería de funcionarte bien

Funciona perfecto en Powershell 👍🏽
