### ISSUE TITLE
Problemas de rendimiento al desactivar la 'Aceleración por hardware' en el navegador

### ISSUE THREAD

**Issue by morcxlla** [midudev/la-velada-web-oficial#334]
# Problema

El efecto del humo, utiliza al GPU para renderizarse, por lo que al desactivar la 'aceleración por hardware' se laguea la pagina entera

## Con
https://github.com/midudev/la-velada-web-oficial/assets/68124533/2092c4d3-6bac-4c9b-852d-fb4120a38303

## Sin
https://github.com/midudev/la-velada-web-oficial/assets/68124533/9ce47f32-1926-4e02-9c4d-a0ceae4c5549

**Comment by joelmh-112** [comment]
Ostras, la verdad es que tiene sentido que pase... hay muchas animaciones y efectos. Intentaré mirar a ver si hay alguna manera de detectar si esta activado y así poder desactivar las más pesadas en funcion de esa detección.

Gracias por hacer tanto testing y ayudarnos a poder hacer la mejor web de la velada IV!

Sigue moviendo esas manitas!! 🚀

**Comment by Thakisis** [comment]
Esperar mover algo medianamente complejo sin aceleracion por hardware es un poco complicado.

 La gpu es una de las piezas de hardware que mas potencia tiene no le veo sentido a renunciar a esa potencia.

 No le veo ningun sentido a preveer un escenario casi imposible es mas probable que un usuario use Ie9 (que por cierto si tiene aceleracion por hardware)  a que entre con la aceleracion desactivada.

**Comment by morcxlla** [comment]
No es correcto, muchos navegadores (como chrome) consumen recursos innecesarios, principalmente en el mundo del gaming (como la gran mayoria de seguidores de Ibai) por lo que se desactiva esta funcion.
Aparte, tambien puede generar otros problemas, por ejemplo, a mi, al tenerla activada, las web de streaming como youtube, por defecto se pone la calidad de los videos a 420p, o en plataformas como netflix o prime video, al poner el navengador en segundo plano, se laguea el video o se desincroniza del sonido.
Y muchas otras cosas que pueden causar que el usuario tenga la función desactiva, como puede ser que el navegador o dispositivo no sean compatibles, o que simplemente este desactivada por defecto.
