### ISSUE TITLE
Idea para el diseño de la sección de visualización de luchadores

### ISSUE THREAD

**Issue by MarcoAnarmo** [midudev/la-velada-web-oficial#335]
Buenas noches, yo tan solo quería aportar una idea que me ha parecido interesante para el siguiente diseño de la sección de selección de luchadores

<img width="649" alt="Captura de pantalla 2024-03-07 a las 23 31 36" src="https://github.com/midudev/la-velada-web-oficial/assets/93273882/1c622df9-8693-4b2d-a030-9f96c14ccb59">

Nada más verlo se me ha venido a la cabeza esta publicación de twitter de Carmen Ansio (https://x.com/carmenansio/status/1765095450405700056?s=20) que me parece que encajaría a la perfección si se ajusta un poco al hacer la animación cuando se selecciona el luchador en lugar de hacer hover como se ve en la demo.

Además, acabo de darme cuenta de que fue algo que hizo en la última MiduConf. Dejo el enlace por aquí https://codepen.io/carmenansio/pen/eYbEOLM

Espero que sirva de ayuda y muchas gracias por leerme!!

**Comment by joelmh-112** [comment]
Buaaah! Que pasada!! Hoy he estado trabajando en la selección de luchadores (responsive y he añadido algo más), tenéis la PR por si la queréis ver. La verdad que me parece muy chulo. A lo mejor mañana pruebo de implementar-lo a ver que tal queda.

Muchas gracias por aportar estas pedazo de ideas! 🚀

**Comment by joelmh-112** [comment]
Holaa de nuevo! Cierro la issue ya que al final el diseño aprobado es uno distinto como puedes ver en el readme del proyecto.

Siento mucho que al final se haya modificado. Igualmente muchisimas gracias por aportar tus ideas y sigue moviendo esas manitas!! 🚀
