### ISSUE TITLE
Movimiento raro en la sección de SelectYourBoxer

### ISSUE THREAD

**Issue by Edier-Gama** [midudev/la-velada-web-oficial#355]
# Pre-requisitos

- [Sí ] Estoy corriendo la última versión.
- [Sí] He revisado si ya hay un issue creado con las mismas características.

# Comportamiento esperado

El componente no debería tener movimientos raros en ninguna previsualización

# Comportamiento actual

Al bajar a cierto nivel, y pasar el mouse por el luchador, se genera un movimiento raro que creo que es ocasionado por la bandera

## Pasos para reproducirlo

[video velada.webm](https://github.com/midudev/la-velada-web-oficial/assets/96151177/d3d8ee8a-e957-4936-b3e0-98db926ea4a0)

**Comment by Trewqa** [comment]
No todas las banderas tienen la misma relación de aspecto de manera oficial por lo que habría que encapsular la imagen o fijarla en altura.

Con este recurso te puedes descargar las banderas con la misma altura y ancho variable si no queremos preocuparnos mucho:
https://flagpedia.net/download/images

**Comment by joelmh-112** [comment]
Ostraas!! He visto la issue ahora, ya que se me encargó hacer un poco responsive y mejorar la selección de luchadores.

Dejo la PR que he hecho por aquí, por si os apetece revisar (no está aprobada por @midudev ni mucho menos pero cumple los requisitos del figma)

 https://github.com/midudev/la-velada-web-oficial/pull/385

Muchas gracias por ir revisando todo, sois unas máquinas! 🤖
