### ISSUE TITLE
Una idea para la selección de boxeadores - diseño en Figma

### ISSUE THREAD

**Issue by yessenia22c** [midudev/la-velada-web-oficial#364]
Hola, Esta es una posible idea de diseño la he hecho un poco rápido. 
Como sugerencia la selección de personaje del Juego Tekken 7 también me parecería interesante. 

https://www.figma.com/file/wQmIAInODbIaoGvyIKKAsd/Untitled?type=design&node-id=0%3A1&mode=design&t=1Hr32AODBeLSvL1s-1 

![image](https://github.com/midudev/la-velada-web-oficial/assets/65354520/100b22bf-6e64-466f-87c1-5c83769d6bb1)

![image](https://github.com/midudev/la-velada-web-oficial/assets/65354520/cc2aa44d-4d11-4c23-a572-59782fe3a11f)

**Comment by joelmh-112** [comment]
Ostras la verdad es que te ha quedado muy chulo! Lo único que (en mi opinión) no acaba de encajar al 100% con el diseño original de la web (figma, estilos, etc). Adaptado un poquito podría estar muy muy bien! 🔥

**Comment by yessenia22c** [comment]
¡Genial! Lo he actualizado, también habría que ver para los diseños de los demás combates diferentes, por ejemplo, los de 2vs2 y los de los 10 boxeadores (el rey de la pista). Me gustaría aportar con algunas opciones, pero necesitaría los recursos.

**Comment by joelmh-112** [comment]
Supeer!! Ya, al haber modalidades distintas tendriamos que barajar opciones. Nosotros estamos igual, aún no tenemos los recursos así que a ver si La Velada pronto le pasa todo lo que queda!! 🖼️

**Comment by yessenia22c** [comment]
Está bien, cuando estén disponibles pueden compartirnos solo sus recursos (fotos de los boxeadores y demás) y cuenten con nuestros aportes en cuanto opciones de diseño. 💪
