### ISSUE TITLE
Añadir width y height de los svg

### ISSUE THREAD

**Issue by midudev** [midudev/la-velada-web-oficial#366]
Hay una advertencia en Lighthouse sobre las imágenes de los sponsor:
![Captura-2024-03-08 002312](https://github.com/midudev/la-velada-web-oficial/assets/1561955/6d6a7155-76aa-441e-9c83-234d0ef8d28b)

Habría que añadir los atributos width y height de los svg.
Lo podríamos añadir en el archivo consts/sponsors.ts.
Y al hacer el loop, añadirlo en la etiqueta <img>.

Luego hay que asegurarse que igualmente se ve bien el svg en todas las resoluciones.

**Comment by joelmh-112** [comment]
De acuerdo! Lo revisamos mañana

**Comment by AlejandroSuero** [comment]
Si alguno de los cambios como la `interface Sponsors` no os bienvenida, comentádmelo.

Se agradecen críticas https://github.com/midudev/la-velada-web-oficial/pull/388

**Comment by joelmh-112** [comment]
Muchas gracias @AlejandroSuero, te dejo la ref de tu PR por aquí ya que te he contestado.

A mover esas manitas!! #388
