### ISSUE TITLE
Sugerencia: Usar componente Image o Picture de astro para las imagenes.

### ISSUE THREAD

**Issue by jct301** [midudev/la-velada-web-oficial#371]
## Descripción
Los componentes Image y Picture ofrecen mejoras en rendimiento a las imágenes en astro, además de más carácteristicas.

## Documentación
- Adjunto link de documentación de componente Image: [image-astro](https://docs.astro.build/es/guides/images/#image--astroassets)
- Adjunto enlace de documentación de componente Picturue: [picture-astro](https://docs.astro.build/es/guides/images/#picture-)

### Componente Image
![image](https://github.com/midudev/la-velada-web-oficial/assets/154246305/753829d2-7c35-49d0-8b5d-a527542066b2)
### Componente Picture
![image](https://github.com/midudev/la-velada-web-oficial/assets/154246305/3fa61e40-fd9f-48c8-b4d3-6e4e64934b79)

## Cuando Image o img
![image](https://github.com/midudev/la-velada-web-oficial/assets/154246305/2a7f9c10-9f8f-4cfd-9b0f-93e48f2566f3)

**Comment by soyricardodev** [comment]
Muy buena idea, tambien implicaria que hay que pasarlo a la carpeta `assets` dentro de `src` segun la documentacion dice, voy a trabajar en eso para hacer una pr

**Comment by joelmh-112** [comment]
Ostras, no sabia que astro ya venia con un componente como éste! Lo tengo que investigar porque tiene buena pinta. 

Podría ser el equivalente de NextJS pero con astro? 🤔  (así para que lo relacione un poco hahah)

Sigue moviendo esas manitas!! 🚀

**Comment by soyricardodev** [comment]
> Ostras, no sabia que astro ya venia con un componente como éste! Lo tengo que investigar porque tiene buena pinta.
> 
> Podría ser el equivalente de NextJS pero con astro? 🤔 (así para que lo relacione un poco hahah)
> 
> Sigue moviendo esas manitas!! 🚀

Si es similar al de Next. Mejor si lo haces tu, debes tener acceso a todas las imagenes para hacerlo apropiadamente.

**Comment by Facug03** [comment]
Buenas, yo estuve intentando utilizarlo agregando los widths y sizes para una mejor optimización, al poner tamaños más chiquitos la imagen pesaba menos, por ejemplo en mobile, pero en desktop al poner la imagenes al tamaño original para que se vean bien la optimización de Astro me dejaba las imágenes más pesadas que la original, probé tanto con Sharp como con Squoosh y ninguna me dio un buen resultado

**Comment by JLex11** [comment]
Creo que el componente Image no sera necesario ya que estamos optimizando las imagenes a mano y las unicas ventajas serian el prefetching que agrega el componente y el manejo de cache pero es algo que tambien podemos hacer, ademas que si se desplega en vercel con ese componente, puede llegar a cobrar por las optimizaciones.
