### ISSUE TITLE
Propuesta para la sección de boxeadores

### ISSUE THREAD

**Issue by soyluisarrieta** [midudev/la-velada-web-oficial#376]
Estuve viendo el diseño de los boxeadores en figma: 
https://www.figma.com/file/rPLkujuJW5FFftBYzyhf0G/LA-VELADA-IV?type=design&node-id=4%3A2&mode=design&t=9LlVziMiQe9HYWVk-1

_Originally posted by @ironnall in https://github.com/midudev/la-velada-web-oficial/issues/370#issuecomment-1986095955_

**Comment by ironnall** [comment]
Gracias @soyluisarrieta :3  ... Añadiendo, la idea del diseño es continuar el estilo inclinado de los botones principales.... tambien agregé las flechas porque siento que se relacionan más con el estilo actual.... La selección de los boxeadores lo hice en vertical para que puedan encajar todos e inclinados para continuar con el estilo de la página. Es una de mis primeras contribuciones que hago en github, espero les ayude c:

**Comment by joelmh-112** [comment]
Buaah!! Esta super chulo el diseño la verdad. A ver que opinan el resto de la comunidad!

Seguid así 🚀

**Comment by johnsi15** [comment]
Esta bastante chévere la propuesta del diseño.

**Comment by draudediaz** [comment]
Disculpad, yo un problema que veo en todas las propuestas que hacéis para la presentación de boxeadores és que no hay referencia al combate que va a realizar. Es decir si se selecciona "El Mariana" tendria que haber algun hover o algo al personaje de plex para saber quien es el contrincante. 

Es mi primera aportación, lo siento si ya lo habéis hablado y no lo he visto. 

Un saludo

**Comment by alexisartigas** [comment]
https://www.figma.com/file/IChR5twugM9Mu57nu6nYK9/VS-IDEAS?type=design&node-id=0%3A1&mode=design&t=ADPKnGH8RERzNdZs-1
![image](https://github.com/midudev/la-velada-web-oficial/assets/3688678/6de3753b-d409-4011-9206-fb3c990a0133)

**Comment by draudediaz** [comment]
Sí, pero yo digo en la pieza de selección de boxeador que aparece solo uno en el centro. Ahí yo pondría un hover clarito al (o a los) contrincantes.

**Comment by AlejandroSuero** [comment]
@alexisartigas un pequeño cambio respecto a ese diseño, sería que el recuadro con los datos fuera del color del fondo y los títulos de información en el `accent-color`.

Así se evita que haya peor visualización en contraste con las banderas.

**Comment by alexisartigas** [comment]
> @alexisartigas un pequeño cambio respecto a ese diseño, sería que el recuadro con los datos fuera del color del fondo y los títulos de información en el `accent-color`.
> 
> Así se evita que haya peor visualización en contraste con las banderas.

@AlejandroSuero algo así?

![Desktop VS-1](https://github.com/midudev/la-velada-web-oficial/assets/3688678/d44a4e94-331a-4c09-a9aa-6ea3161c89ca)

**Comment by AlejandroSuero** [comment]
Así creo que queda perfecto @alexisartigas.

Quizás haya alguna queja por consistencia en los botones, pero a lo mejor al ser una sección distinta estaría aceptado.

**Comment by soyluisarrieta** [comment]
@alexisartigas No está nada mal, pero sería bueno verlo para dispositivos móviles para evaluar su adaptabilidad.

**Comment by alexisartigas** [comment]
@soyluisarrieta Si justo he estado viendo eso, para que sea de fácil adaptación a móviles.

![Mobile](https://github.com/midudev/la-velada-web-oficial/assets/3688678/3af691e2-6e50-40d3-a246-850b142921f3)

Se aceptan críticas.

**Comment by soyluisarrieta** [comment]
@alexisartigas Mis comentarios serían los siguientes:

1. La presencia de la X parece redundante, ya que se repite en el logo y en el fondo.
2. ¿El logo realmente añade valor? Podría estar ocupando espacio que podrían utilizar los peleadores.
3. En la versión móvil, la sección no parece estar unificada como en la versión de escritorio. Sería útil idear una solución que mantenga la cohesión visual en ambas versiones.
4. La duplicación de los botones "GANADOR" podría evitarse mediante un único switch central con iconos de flecha.
5. Para mejorar la interactividad, se podría considerar la opción de reducir la escala de tamaño y opacar o desaturar el color del peleador que no se esté seleccionando al pasar el cursor sobre ellos.

Para ilustrar estas ideas, he encontrado una referencia que podría servir de inspiración:

![image](https://github.com/midudev/la-velada-web-oficial/assets/88900534/8b190c57-75b7-45bb-8b53-b6c0c3fd0aa1)

Observa cómo todos los elementos están integrados de manera fluida, creando una sensación de unidad. Además, nota como se destaca el tamaño imponente de los peleadores, otorgándoles un total protagonismo en esa sección.

Me gusta también el detalle de añadir el botón de compartir pronóstico 🤯

**Comment by alexisartigas** [comment]
@soyluisarrieta Gracias por tus comentarios y sugerencias, tomé algunas. 👍 No soy experto en UX / UI me gusta el diseño mi fuerte es el Backend en otras tecnologías. Saludos.

![WIN LEFT](https://github.com/midudev/la-velada-web-oficial/assets/3688678/b7731de2-93ab-4d99-9d7e-d4be5ba4a05a)
![WIN RIGTH](https://github.com/midudev/la-velada-web-oficial/assets/3688678/63c031f2-140b-4a8d-963c-6d4a05d9e270)
![iPhone 14   15 Pro Max - 1](https://github.com/midudev/la-velada-web-oficial/assets/3688678/9bf48128-3c63-4a12-986c-9fb39ef0ac0c)
