### ISSUE TITLE
idea para presentación de los peleadores

### ISSUE THREAD

**Issue by antmonsep** [midudev/la-velada-web-oficial#387]
Hola! me salte absolutamente todos los pre requisitos y requisitos porque no es ningún bug, quería escribir acá porque me gustó el video del midu en twitch sobre esto y quise transmitir más o menos la idea que tengo, que igual quizás no sirva, quizás sí?

Cuando vi el video del midu pensé en street fighters, y buscando imágenes de la selección de peleadores encontré esta
![image](https://github.com/midudev/la-velada-web-oficial/assets/69049114/039fa057-cff0-4cc2-b08e-85be9699801a)

pensé en mostrar la información similar como presentan a los peleadores en la UFC
![image](https://github.com/midudev/la-velada-web-oficial/assets/69049114/bb2ceb8b-9b93-4a30-bc6f-01fee40efa94)

falto el estilo cascada de las miniaturas, las miniaturas redondeadas o en esta forma, quizás un efecto como este de zoom, donde la miniatura seleccionada resaltará sobre las demás
![image](https://github.com/midudev/la-velada-web-oficial/assets/69049114/01ee4978-8019-4cbe-a9b9-5f5c67a1c524)

aquí está mi esfuerzo por hacerlo en figma (primera vez que uso así que perdonen la referencia)
![image](https://github.com/midudev/la-velada-web-oficial/assets/69049114/bf30f36b-a0f2-4b96-b08b-085282818b76)

gracias por leer esto y ya ando esperando para ver como quedará finalmente! saludos c:

**Comment by Thakisis** [comment]
creo que es mejor ordenarlos segun el calendario mostrar una fila y con un boton de drawer desplegar los restantes. Si tengo tiempo creare un prototipo,  pero ahora mismo me estoy peleando con webgl

**Comment by midudev** [comment]
Gracias por las ideas, crack! Cierro que ya hemos hecho estos diseños!
