### ISSUE TITLE
Valoren activar las Discussions de github. 

### ISSUE THREAD

**Issue by gsi-chao** [midudev/la-velada-web-oficial#433]
Seria bueno activaran las dicussions de github para no contaminar la sección de issues. @midudev
Ya que estamos, pudieran enviarme el diseño de figma?
Saludos

**Comment by AlejandroSuero** [comment]
Estaría bien la discussions y también, que no sé si está, un canal de discord.

**Comment by midudev** [comment]
Gracias por la idea, pero tampoco creo que se genere tanta discusión y si es así, mejor usar Discord.
