### ISSUE TITLE
design: store section proposal 💄

### ISSUE THREAD

**Issue by AlejandroSuero** [midudev/la-velada-web-oficial#435]
No sé si el ir a la tienda oficial, es tema de diseño el que sea un botón/link.

Pero se me ocurre que se podría añadir una sección tipo carrousel para que el usuario vea alguno de los productos de la tienda, y así incitar más a la compra.

Se podría usa alguna imagen como fondo del estilo del diseño de los iconos de los links y de la selección de los luchadores, el estilo dibujado, para crear consistencia.

<p align="center">
 <img width="298" alt="Screenshot 2024-03-11 at 16 46 18" src="https://github.com/midudev/la-velada-web-oficial/assets/71392160/2cd36179-49d1-47a9-b372-4db11cc689f6" />
</p>

Puedo encargarme de crear algún diseño en figma para usar como referencia si se aprueba.

**Comment by midudev** [comment]
He añadido el enlace de la tienda en el Header directamente.

**Comment by AlejandroSuero** [comment]
@midudev Me refiero a una sección a parte del link en la landing que tenga una especie de expositor/carrusel, con las imágenes (si nos las ceden) de la tienda. Pero sin el fondo y hacer uso de elementos como la imagen del issue, tipo dibujo para que haya coordinación en el diseño.

Me podría incluso encargar del diseño de las imágenes con el estilo de dibujado por encima. Dejo abajo algunos dibujos/pinturas/ilustraciones hechas por mi.

- Imágenes de la tienda oficial:

![imágenes tienda oficial de la velada 1](https://github.com/midudev/la-velada-web-oficial/assets/71392160/84ac7571-e12d-43ff-a5b5-f05e87845ebf)

![imágenes tienda oficial de la velada 2](https://github.com/midudev/la-velada-web-oficial/assets/71392160/e41ccab7-e52c-4ad0-b728-9734fab957b4)

- Imágenes de dibujos/ilustraciones propias:

![zombie-fox-concept](https://github.com/midudev/la-velada-web-oficial/assets/71392160/29401d8d-5556-4bc0-aeb9-f9698885a71f)

![touka-tokyo-ghoul-fighting-mode](https://github.com/midudev/la-velada-web-oficial/assets/71392160/189d5345-b30e-45fe-834d-925c6b72bdf7)

![happy-girl](https://github.com/midudev/la-velada-web-oficial/assets/71392160/16ffdfee-2927-482b-b9b9-6529023facb6)

![vayne-project-skin-close-up](https://github.com/midudev/la-velada-web-oficial/assets/71392160/e9f67991-39db-4786-8d4e-0262cc3c7526)

![japanese-girl-from-trip1](https://github.com/midudev/la-velada-web-oficial/assets/71392160/ac8d2a4e-2a39-424b-9403-32a87e39ff0a)

![japanese-girl-from-trip2](https://github.com/midudev/la-velada-web-oficial/assets/71392160/020b8c21-6a60-4709-b3fc-6a3216a3813a)

![japanese-girl-from-trip3](https://github.com/midudev/la-velada-web-oficial/assets/71392160/917dc3f3-2f0c-4e22-b7c6-97ef922a90e8)

![rave-animation-clean-up](https://github.com/midudev/la-velada-web-oficial/assets/71392160/4109ff31-1623-455f-affa-58a0244ee1f0)
