### ISSUE TITLE
Overflow visible

### ISSUE THREAD

**Issue by AlejandroSuero** [midudev/la-velada-web-oficial#450]
# Pre-requisitos

- [X] Estoy corriendo la última versión.
- [X] He revisado si ya hay un issue creado con las mismas características.

# Comportamiento esperado

No debería mostrarse el scroll en el eje X.

# Comportamiento actual

Se muestra el scroll en el eje X debido a overflow de elemento.

# Información del bug (si corresponde)

Creo que está relacionado con el fix de la PR cerrada #445 y el issue abierto #415.

Añadiendo overflow hidden:

<img width="1152" alt="Overflow-hidden-on" src="https://github.com/midudev/la-velada-web-oficial/assets/71392160/637a0f3b-df9f-43f1-82e7-776b2fea385c">

Como está ahora:

<img width="1152" alt="Overflow-hidden-off" src="https://github.com/midudev/la-velada-web-oficial/assets/71392160/a69d2a07-cc15-4898-b743-913468fbcb82">

## Pasos para reproducirlo

1. `pnpm run dev` o ir [lavelada.es](https://lavelada.es/)
2. Abrir `dev-tools` para reducir la pantalla

## Contexto

- Navegador: Firefox, Chrome, Safari.
- Versión del navegador: La última estable.
- Sistema operativo: Windows, MacOS, Linux.

**Comment by AlejandroSuero** [comment]
También haría que el efecto glow introducido por @midudev, se cortase. Como se puede observar en la esquina izquierda del "reproductor".

<img width="1152" alt="Screenshot 2024-03-12 at 13 31 49" src="https://github.com/midudev/la-velada-web-oficial/assets/71392160/4a9f6fb3-224e-4f12-805f-1b01a83c2efb">

**Comment by AlejandroSuero** [comment]
Como propuesta, creo que sería mejor tener el logo como elemento separado en vez de como `background-image: url(...)`.

Si alguien quiere hacerlo, si no, puedo hacerlo yo.

**Comment by dresandev** [comment]
Hola Alejandro, el overflow actual es causado por el componente Date usado en el section Countdown, por lo que técnicamente el quitar el overflow-x del body si es lo que hace que se vea el scroll horizontal en este caso es mejor controlar el overflow ya sea en el componente Date o en el section Countdown. El usar el overflow hidden en el body o html puede causar diversos problemas, entre ellos el bloqueo del pull to refresh o que el position sticky no funcione como se espera.


https://github.com/midudev/la-velada-web-oficial/assets/79766563/a3eb3472-6a38-450e-ba43-09a56d3144ab

**Comment by AlejandroSuero** [comment]
@dresandev cierro la issue y dejamos la tuya, o la dejo abierta como referencia hasta arreglarlo?

**Comment by dresandev** [comment]
Dejemos esta, ya que la otra hacía referencia al 'pull to refresh' y en esta tratamos el tema del overflow. Intento solucionarlo y referencio esta issue en el PR.

**Comment by AlejandroSuero** [comment]
> > @dresandev cierro la issue y dejamos la tuya, o la dejo abierta como referencia hasta arreglarlo?
> 
> Dejemos esta, ya que la otra hacía referencia al 'pull to refresh' y en esta tratamos el tema del overflow. Intento solucionarlo y referencio esta issue en el PR.

Perfecto, gracias por el feedback y encargarte 🫡.

**Comment by dresandev** [comment]
> > > @dresandev cierro la issue y dejamos la tuya, o la dejo abierta como referencia hasta arreglarlo?
> > 
> > Dejemos esta, ya que la otra hacía referencia al 'pull to refresh' y en esta tratamos el tema del overflow. Intento solucionarlo y referencio esta issue en el PR.
> 
> Perfecto, gracias por el feedback y encargarte 🫡.

Hola, ya se realizó el merge de la PR corrigiendo el problema, solo que hice referencia a esta issue junto a una PR y esta issue no se cerró automáticamente, por lo que ya puedes cerrarla. Gracias.

**Comment by AlejandroSuero** [comment]
Vale, gracias por solucionarlo @dresandev 🤩.
