### ISSUE TITLE
Bug: Contenido general de la pagina: no centrado

### ISSUE THREAD

**Issue by JJozef** [midudev/la-velada-web-oficial#456]
# Pre-requisitos

- [x] Estoy corriendo la última versión.
- [x] He revisado si ya hay un issue creado con las mismas características.

# Comportamiento esperado

El contenido debería estar centrado, pero por algún motivo este esta desplazado a la izquierda, en `móvil`.

# Comportamiento actual

![M2](https://github.com/midudev/la-velada-web-oficial/assets/101532359/c650888e-415a-4a02-9f6f-f5ebcf458fac)

![M3](https://github.com/midudev/la-velada-web-oficial/assets/101532359/47358cbe-1aaf-4acd-a92b-1919ccf6f47d)

# Información del bug (si corresponde)

## Pasos para reproducirlo

1. Solo entrar a la página en `móvil`

## Contexto

- Navegador: Safari - IOS.

**Comment by dresandev** [comment]
Hola, mira el issue #450 
Por eso la no se ve correctamente en móviles

**Comment by JJozef** [comment]
Repetida.
