### ISSUE TITLE
Fuente Atomic sin preload, al recargar la pagina hace un cambio del estilo de fuente brusco

### ISSUE THREAD

**Issue by Cristian021195** [midudev/la-velada-web-oficial#462]
Estoy corriendo la última versión y ya revisé en las ramas publicadas.
-Si he revisado si ya hay un issue creado con las mismas características y no la hay.

# Comportamiento esperado

Lo ideal es que no haga el cambio brusco de fuente, menos en el primer contenido de la pagina, donde dice "twitch.tv/ibai"

# Comportamiento actual

Hace el cambio brusco debido a que no precarga la fuente Atomic.woff2

# Información del bug (si corresponde)

El inconveniente este en el archivo src/components/SEO.astro.
No conozco astro, pero por algun motivo una fuente si la carga con preload desde node_modules, pero no encontré la ruta para la fuente atomic. de todas formas se soluciona incluyendola de manera absoluta, el build no dio problemas al respecto.

## Pasos para reproducirlo

1 - Recargar la pagina, sin importar que limpies la cache o no, igual hace el cambio brusco, el navegador por defecto no cachea la fuente

## Pasos para solucionarlo

agregar en el archivo src/components/SEO.astro

` import atomic from "/fonts/atomic.woff2" `
`< link rel="preload" href={atomic} as="font" type="font/woff2" crossorigin >`

## Contexto

Chrome y Microsoft Edge
Versión del navegador: ultima
Sistema operativo: Windows

## Logs de error (si corresponde)

Sin logs

**Comment by Sergio401** [comment]
Se implementó tu sugerencia en el PR #469

**Comment by Sergio401** [comment]
Hola @Cristian021195, ya se añadió la solución, creo que se puede cerrar el Issue

**Comment by Cristian021195** [comment]
perfecto, gracias!
