### ISSUE TITLE
:bulb: Sugerencia de idea para el diseño de los boxeadores

### ISSUE THREAD

**Issue by joanbric** [midudev/la-velada-web-oficial#472]
# :bulb:  Idea para la sección de boxeadores

Como alternativa a la idea que se tiene actualmente propongo envolver al boxeador principal, en un marco hecho con las imágenes pequeñas de todos los boxeadores.

![boxeadores](https://github.com/midudev/la-velada-web-oficial/assets/16466071/bec8b4da-0675-4f60-8c05-568cc62db3b8)

Y en la versión móvil tendríamos dos filas una arriba y una abajo.

![iPhone 14   15 Pro - 2](https://github.com/midudev/la-velada-web-oficial/assets/16466071/1a39c075-4108-46fb-90ae-7b1e6cb0de87)

El siguiente sería el comportamiento de la sección:

[boxeadores-ejemplo.webm](https://github.com/midudev/la-velada-web-oficial/assets/16466071/19df530b-4295-4488-a78b-c0ad43393f2f)

Con mucho gusto haré la PR si les parece que es buena idea. Me gustaría conocer sus opiniones.

**Comment by midudev** [comment]
¡Gracias por la idea! Al final haremos que aparezca el boxeador en el centro y columnas a los lados. Abrazote!
