### ISSUE TITLE
Posible layout/content shift en la carga inicial

### ISSUE THREAD

**Issue by AlejandroSuero** [midudev/la-velada-web-oficial#513]
# Pre-requisitos

- [X] Estoy corriendo la última versión.
- [X] He revisado si ya hay un issue creado con las mismas características.

# Comportamiento esperado

Cargar las imágenes y textos sin transición.

# Comportamiento actual

Se carga el contenido con lo que parece una animación de movimiento, no sé si es el comportamiento esperado o un problema a solucionar.

https://github.com/midudev/la-velada-web-oficial/assets/71392160/82be41bb-2e97-4906-b02a-1a52b37c2054

> Grabado en el navegador Brave, probado en Safari y Google Chrome

# Información del bug (si corresponde)

No se nota mucho si no ralentizas la carga, pero es visible aunque muy rápida a la hora de hacer un uso con la carga por defecto.

## Pasos para reproducirlo

1. Usar un navegador, reducir el tipo de carga de internet para ralentizar la carga y ver como se produce esta carga del contenido con una animación.
2. Recargar y comprobar si tiene el efecto descrito.

## Contexto

Brave y Safari sin extensiones, Chrome con extensiones, mismo comportamiento.

- Navegador: Firefox, Chrome, Safari
- Versión del navegador: La última
- Sistema operativo: MacOS, Linux

## Logs de error (si corresponde)

La sección del Header es la afectada, las demás no están comprobadas, pero lo primero que ve el usuario sería la sección Header.

**Comment by midudev** [comment]
A ver si le puedes echar un ojo @joelmh-112

**Comment by joelmh-112** [comment]
Solucionado, he puesto grid en vez de flex, lo que tarda en cargar el logo... con eso no puedo hacer nada. Lo que ahora si reserva bien el espacio para él y entonces no se desplaza.
