### ISSUE TITLE
SelectYourBoxer not responsive

### ISSUE THREAD

**Issue by AlejandroSuero** [midudev/la-velada-web-oficial#529]
No tiene responsividad y se cortan las imágenes en móvil.

<img width="704" alt="Screenshot 2024-03-14 at 12 45 09" src="https://github.com/midudev/la-velada-web-oficial/assets/71392160/36c14b10-9512-402d-8013-bf27bf818b99">

En el vista de ordenador cargan lentas las imágenes también.

**Comment by aruznieto** [comment]
En Mac con safari yo lo veo así

![CleanShot 2024-03-14 at 13 32 43](https://github.com/midudev/la-velada-web-oficial/assets/40019177/0674fa40-a8a7-430b-a0f8-c1c93294721e)

**Comment by AlejandroSuero** [comment]
> En Mac con safari yo lo veo así
> 
> ![CleanShot 2024-03-14 at 13 32 43](https://private-user-images.githubusercontent.com/40019177/312838392-0674fa40-a8a7-430b-a0f8-c1c93294721e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MjgwMDEsIm5iZiI6MTcxMDQyNzcwMSwicGF0aCI6Ii80MDAxOTE3Ny8zMTI4MzgzOTItMDY3NGZhNDAtYThhNy00MzBiLWEwZjgtYzFjOTMyOTQ3MjFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDE0NDgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NWIxNGFiZDBmZjY0ZWQwNTMyNmM0ZWU2ZThiOWVjNTcxM2Y5M2MzN2Q0NDE0ZmQxOThkZTE2MDliMTZiNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LZSHaP5fgRPROA4Sto-Gj0kqiVZlRiQ38VgRBodT32U)

Esto parece estar solucionado, al menos en mi Safari.

**Comment by AlejandroSuero** [comment]
<img width="704" alt="Screenshot 2024-03-14 at 15 50 10" src="https://github.com/midudev/la-velada-web-oficial/assets/71392160/b010c543-888f-41cf-b966-ddb26b2191eb">

En móvil sigue teniendo el fallo del recorte de las imágenes. Imagino que estarán con ello.

**Comment by AlejandroSuero** [comment]
> Sí, correcto. En safari ya está bien. En movil a mi no me aparece esa sección

A mí tampoco, pero con la versión responsive del navegador sí hasta tablet, luego desaparece.

**Comment by ErickCSS** [comment]
En una pull request que acabo de realizar arreglé el responsive en el modo Tablet pueden chequearlo. #567

**Comment by AlejandroSuero** [comment]
> En una pull request que acabo de realizar arreglé el responsive en el modo Tablet pueden chequearlo. #567

Sí justo lo acabo de ver, ahora solo falta el móvil, que ni aparece la sección 😅

**Comment by joelmh-112** [comment]
Holaa!! Procedo a cerrar la issue ya que veo que está solucionado.

Seguid moviendo esas manitas!
