### ISSUE TITLE
Problemas con la versión de TypScript

### ISSUE THREAD

**Issue by ErickCSS** [midudev/la-velada-web-oficial#536]
# Pre-requisitos

- [ x ] Estoy corriendo la última versión.
- [ x ] He revisado si ya hay un issue creado con las mismas características.

# Comportamiento esperado

A la hora de correr pnpm run lint, haga el lint sin errores
# Comportamiento actual
Teniendo problemas con la versión de Typescript y @typescript-eslint/typescript-estree

<img width="999" alt="Screen Shot 2024-03-14 at 10 46 16 AM" src="https://github.com/midudev/la-velada-web-oficial/assets/60988586/7f095257-fccf-4c1b-9a97-cddf5f38bce1">

# Información del bug (si corresponde)

## Pasos para reproducirlo

1. Paso 1 
2. Paso 2

## Contexto

- Navegador: Firefox, Chrome, Safari, Microsoft Edge, Opera, etc.
- Versión del navegador: ---
- Sistema operativo: Windows, MacOS, Linux

**Comment by AlejandroSuero** [comment]
El problema con `NodeListOF` debería solucionarse con `globalThis.NodeListOf<HTMLAnchorElement>`.

<img width="951" alt="Screenshot 2024-03-14 at 16 04 41" src="https://github.com/midudev/la-velada-web-oficial/assets/71392160/30784aac-5332-4f64-9ab1-20563e8ad94c">

Los warnings puedes ignorarlos si sabes el porque salen y que vas a hacer con ellos.

**Comment by AlejandroSuero** [comment]
Las variables que no se estén usando, se pueden poner así `name` -> `_name` y así en caso de que se use, o referencias como está o le quitas `_`.

**Comment by AlejandroSuero** [comment]
#532 Debería solucionarlo.

**Comment by marsidev** [comment]
> El problema con `NodeListOF` debería solucionarse con `globalThis.NodeListOf<HTMLAnchorElement>`.

En #495 sugerí arreglarlo con 

```ts
const boxerLinks = [..Array.from(document.querySelectorAll(".boxer-link"))] as HTMLAnchorElement[]
```

pero no fue mergeado porque cambiaba muchos archivos y ponía en conflicto PRs futuras

**Comment by ErickCSS** [comment]
Los he ido arreglando, pero el error del Typescript sigue igual y no me gustaría cambiar algo que luego cree conflictos con las ramas y las futuras

**Comment by AlejandroSuero** [comment]
> Los he ido arreglando, pero el error del Typescript sigue igual y no me gustaría cambiar algo que luego cree conflictos con las ramas y las futuras

Te refieres a la versión de TypeScript? Si es eso, todos tenemos la misma en teoría, @midudev tendría que cambiarla, configurar y ver que no se rompiesen las dependencias.

**Comment by marsidev** [comment]
Lo de TypeScript no es un error sino un warning de una dependencia de ESLint. 

Creo que puede ignorar ya que ESLint está funcionando bien.

**Comment by ErickCSS** [comment]
@AlejandroSuero Si, a eso me refiero, ya que no me deja avanzar porque el linter me anda dando ese error del typescript y supondria que todos tenemos la misma versión

**Comment by AlejandroSuero** [comment]
> @AlejandroSuero Si, a eso me refiero, ya que no me deja avanzar porque el linter me anda dando ese error del typescript y supondria que todos tenemos la misma versión

Pero el linter debería ignorar ese warning a menos que se usen `features` de nuevas versiones que no estén en la que tenemos.

**Comment by marsidev** [comment]
> no me deja avanzar porque el linter me anda dando ese error del typescript

El único error que es obligatorio corregir es el de `NodeListOf`, arriba hay dos posibles soluciones para ello.

Si husky te está dando error (y tu PR está fuera del scope de eso), puedes omitirlo con `git commit -m "your comment" --no-verify`

**Comment by midudev** [comment]
Arreglados los problemas 👍
