### ISSUE TITLE
Problema con el menú de navegación

### ISSUE THREAD

**Issue by TheLokin** [midudev/la-velada-web-oficial#562]
# Información del bug

Menú de navegación no desplegable: En dispositivos móviles, el menú de navegación no se despliega correctamente al hacer clic en el icono de menú.

https://github.com/midudev/la-velada-web-oficial/assets/41437556/a7f3f94b-f039-4a72-9846-4dcdec127c56

**Comment by AlejandroSuero** [comment]
Hola @TheLokin,

El fallo está al momento de abrir, cerrar o en ambos casos?

**Comment by TheLokin** [comment]
> Hola @TheLokin,
> 
> El fallo está al momento de abrir, cerrar o en ambos casos?

en el de cerrar, básicamente cuando haces clic en alguno de los anchor se debería cerrar el menú y el problema es que no lo está haciendo, quedando ahí bloqueado porque el botón para desplegar el menú ya no responde

**Comment by TheLokin** [comment]
también otro fallo que he detectado, que igual debería ir en una nueva issue, es que el logo de la velada en el componente Hero al navegar (actualmente haciendo clic en el anchor de el evento) se pierde la animación

**Comment by AlejandroSuero** [comment]
> también otro fallo que he detectado, que igual debería ir en una nueva issue, es que el logo de la velada en el componente Hero al navegar (actualmente haciendo clic en el anchor de el evento) se pierde la animación

Ciertamente, porque en teoría no debería hacer eso, tiene que ser algo relacionado con el `AnimatedX.astro` o el `Hero.astro` porque es como que se desactivan esas animaciones. Pero no las demás.
