### ISSUE TITLE
Problema con el fondo al hacer resize de la web

### ISSUE THREAD

**Issue by anxxt** [midudev/la-velada-web-oficial#568]
# Comportamiento esperado

El fondo debería de actualizarse inmediatamente después de hacer resize de la página.

# Comportamiento actual

Actualmente no se actualiza inmediatamente dando lugar a que se vea parte de la página sin el efecto al hacer el resize de la página.

https://github.com/midudev/la-velada-web-oficial/assets/60880681/12a01e99-24ab-4f7c-8c37-44434cb04478

## Pasos para reproducirlo

1. Se puede reproducir al hacer resize de la página de cualquier forma. Por ejemplo, abriendo las herramientas de desarrollador o teniendo la ventana del navegador pequeña y haciéndola más grande.

## Contexto

- Navegador: Chrome
- Versión del navegador: 122.0.6261.129 (Build oficial) (64 bits)
- Sistema operativo: Windows

**Comment by Edier-Gama** [comment]
Debe estar causado por el efecto ruido. Quizá haya que optimizarlo
