### ISSUE TITLE
Problema Header volver home

### ISSUE THREAD

**Issue by EduWTR** [midudev/la-velada-web-oficial#578]
# Pre-requisitos

- [x] Estoy corriendo la última versión.
- [x] He revisado si ya hay un issue creado con las mismas características.

# Comportamiento esperado

Volver al Home (el Evento) , siguiendo el enlace del header.

# Comportamiento actual
En la pantalla completa, 'el evento' del header vuelve al '/', pero si abrimos devtool(o alguna resolución inferior hasta los 1024 pixels), al hacer hover sobre el span del 'el evento', unicamente el span, nos reenvía al mismo boxeador(actualmente , única sección habilitada),o supongo que la pantalla que estamos viendo ( #main-content ) , pero no vuelve al home (/)

# Información del bug (si corresponde)

## Pasos para reproducirlo

1. Abrir devTools, o bajar entre 1170 pixeles / 1024 pixeles, ya que después pasaría a la versión burguer

## Contexto

- Navegador: Firefox, Brave(1.64.97)
- Sistema operativo: Linux

## Capturas ( en la captura no sale el puntero, pero estaría siempre sobre el span 'el evento')
versión escritorio(1358px):
![image](https://github.com/midudev/la-velada-web-oficial/assets/139919492/a4a14ed3-d836-4ad3-922f-69e1ee03a736)

versión escritorio(1170px hasta 1024px)
![image](https://github.com/midudev/la-velada-web-oficial/assets/139919492/0e82b4a7-a943-47b4-a510-b5bdd23b49ae)

![image](https://github.com/midudev/la-velada-web-oficial/assets/139919492/c480bf3d-3882-4774-b5b7-ed7ada7da4e0)

**Comment by AlejandroSuero** [comment]
Podría ser por el skip-to-main que introduje en el Layout. Lo suyo sería poner la clase de event pointers none cuando no esté en focus y ponerla a pointer cuando sí esté.

**Comment by EduWTR** [comment]
Es extraño! te iba a decir que eran las letras, pero, puede ser que tenga que ver con la resolución?
###
1076PX:(es todo el span)
![image](https://github.com/midudev/la-velada-web-oficial/assets/139919492/c7b096ea-796c-4129-9021-0ed57d38cfaf)
###
1144px(el límite esta entre la N y la T)
![image](https://github.com/midudev/la-velada-web-oficial/assets/139919492/1886a1d4-cf88-4beb-9774-ad80ac79ea73)
![image](https://github.com/midudev/la-velada-web-oficial/assets/139919492/57f02aa4-3017-41a3-a2a8-8838ad13b299)
###
1174px: casi nos vamos a la E, para que aparezca el #main-content
![image](https://github.com/midudev/la-velada-web-oficial/assets/139919492/dcbcea18-c267-4b37-8d80-1f09403ff8c3)

**Comment by AlejandroSuero** [comment]
Es por lo que dije antes, porque hace que te lleve a `#main-content`
