### ISSUE TITLE
Permitir retornar a la página de Inicio sin necesidad de darle al botón de retroceder del navegador (back button)

### ISSUE THREAD

**Issue by eideard-hm** [midudev/la-velada-web-oficial#582]
# Pre-requisitos

- [x] Estoy corriendo la última versión.
- [x] He revisado si ya hay un issue creado con las mismas características.

# Comportamiento esperado

Cuando me redirecciona al detalle de cada boxeador no tengo forma desde la página de retroceder; por el contrario toca con la barra del navegador. Seria buena idea el poder tener la opción de retroceder desde dentro de la app

**Comment by AlejandroSuero** [comment]
De momento está el link al evento en el header que direcciona a la página inicial.

**Comment by eideard-hm** [comment]
Al retroceder con esa opción ocurre este error reportador aquí: #609
