### ISSUE TITLE
Sugerencia: Mover el audio 'son-robots-ibai.mp3' fuera del proyecto

### ISSUE THREAD

**Issue by zackproject** [midudev/la-velada-web-oficial#597]
# Pre-requisitos
- [x] Estoy corriendo la última versión.
- [x] He revisado si ya hay un issue creado con las mismas características.

# Comportamiento actual
Al usar el KonamiCode 'midu' se carga el audio [son-robots-ibai.mp3](https://lavelada.es/sounds/son-robots-ibai.mp3) dentro del proyecto.

# Información del bug (si corresponde)
Como explicaste en el video [Netlify le cobra $104,500 por una Página Web](https://www.youtube.com/watch?v=JIFREanXdRI) un usuario podría pedir el audio en bucle. Se podria poner el audio en una web externa de [lavelada.es](https://lavelada.es/)

## Pasos para reproducirlo
Llamar varias veces el mismo archivo [son-robots-ibai.mp3](https://lavelada.es/sounds/son-robots-ibai.mp3).

## Logs de error (si corresponde)

![image](https://github.com/midudev/la-velada-web-oficial/assets/44408822/87366490-e0d1-44b7-8c1d-ca9d9e070f62)

**Comment by AlejandroSuero** [comment]
Se podría hacer eso o tener las rutas, a los archivos estáticos, protegidas. No sé ahora cuál es la manera en la que se controlan las rutas en Astro.

Porque de la manera que está hecho ahora puedes acceder a la ruta, pero al hacer la llamada con el código "midu", sólo se carga una vez al no ser una llamada a una ruta externa, al contrario que las imágenes de los contribuidores.

![image](https://github.com/midudev/la-velada-web-oficial/assets/71392160/c415138d-968e-454d-a450-7efed9a6ec63)

> [!Note]
>
> En la imagen se llama dos veces a `contributors` pero solo una vez al audio.

No sé exactamente cuál sería mejor forma realmente. Porque a no ser que se sacase a un servicio externo a nosotros, no sé cuál sería la diferencia en el riesgo de que alguien pida el audio en bucle.

Si se hiciera de manera externa, pero hosteado por nosotros, tendría que ser pasando alguna API_KEY por los Headers, para hacer que no se pueda pedir en bucle, supongo.

Pero me parece buena idea para una discusión a ver que es mejor en este tipo de situaciones.

**Comment by MattEzekiel** [comment]
Yo no le daría importacia, ya que, La web está en vercel no en netlify como cuenta el video, siendo vercel mucho más generoso en su ancho de banda que netlify, por otro lado, el audio no es un archivo pesado, pesa 211kb y solamente se carga cuando se escribe "midu", si escribes "midu" una y otra vez lo levantará del caché de tu navegador, no hará una petición cada vez que se escriba
![image](https://github.com/midudev/la-velada-web-oficial/assets/50919956/4cf766e0-d157-4c96-92ee-925e4ea25bcd)

Además las imágenes que aparecen en la primera carga ya pesan más que el audio en sí:
![image](https://github.com/midudev/la-velada-web-oficial/assets/50919956/fe5633b3-3e33-4eaa-bd35-d8c6c66032cc)

Por lo tanto no creo que esto genere ningún tipo de problema para la web 😁

**Comment by midudev** [comment]
¡Ya lo hemos movido fuera!
