### ISSUE TITLE
[BUG] Logo animado y Contador dejan de funcionar.

### ISSUE THREAD

**Issue by AlejandroSuero** [midudev/la-velada-web-oficial#609]
# Pre-requisitos

- [X] Estoy corriendo la última versión.
- [X] He revisado si ya hay un issue creado con las mismas características.

# Comportamiento esperado

Al volver a la página principal haciendo click en los elementos de navegación, actuar de manera normal. Logo seguir estando animado y el contador, seguir contando los días que quedan.

# Comportamiento actual

Al volver o no recargar la página principal, el logo animado y el contador dejan de actuar con su comportamiento esperado.

https://github.com/midudev/la-velada-web-oficial/assets/71392160/d58ce644-e0a9-4df0-bf38-a286185bf10c

# Información del bug (si corresponde)

Pareciese ser como si no se activasen los eventos de estos componentes `AnimatedX.astro` y `Date.astro`, en las secciones `Hero.astro` y `Countdown.astro`.

## Pasos para reproducirlo

1. Navegar a https://lavelada.es/
2. Hacer click en el item `EL EVENTO` en `nav`.
3. Ver como el logo animado para.
4. Bajar y ver como el contador se pone a 0.

> [!Important]
>
> Se puede reproducir navegando a la página de uno de los boxeadores y volviendo a la página inicial haciendo click en el `nav`

## Contexto

- Navegador: Firefox, Chrome, Safari.
- Versión del navegador: La última estable de cada uno.
- Sistema operativo: Windows, MacOS, Linux.

## Logs de error (si corresponde)

Secciones afectadas:

- [Hero.astro](https://github.com/midudev/la-velada-web-oficial/blob/main/src/sections/Hero.astro)
- [Countdown.astro](https://github.com/midudev/la-velada-web-oficial/blob/main/src/sections/Countdown.astro)

Componentes afectados:

- [AnimatedX.astro](https://github.com/midudev/la-velada-web-oficial/blob/main/src/components/AnimatedX.astro)
- [Date.astro](https://github.com/midudev/la-velada-web-oficial/blob/main/src/components/Date.astro)

**Comment by joelmh-112** [comment]
Arreglado con la pr #611 .

A seguir moviendo esas manitas!! 🚀
