### ISSUE TITLE
Selección incorrecta del boxeador al momento de volver desde la página de detalle

### ISSUE THREAD

**Issue by chrisdca** [midudev/la-velada-web-oficial#679]
# Comportamiento esperado

1. Hacer click en un boxeador
2. Carga la página sobre detalles del boxeador seleccionado
3. Al hacer click en el botón volver en el navegador debería seleccionar al boxeador que anteriormente vistes su detalle

# Comportamiento actual

1. Hacer click en un boxeador
2. Carga la página sobre detalles del boxeador seleccionado
3. Al hacer click en el botón volver en el navegador, se selecciona un boxeador que no vistes su detalle

## Pasos para reproducirlo

1. Si tu red no presenta lentitud, puedes reproducirlo configurando una red Fast 3G desde la pestaña network de la developer tools
2. Luego hacer click en un boxeador
3. Inmediatamente después de hacer click en un boxeador, ubicar el puntero del mouse sobre un boxeador diferente a lo seleccionado

[issue-boxer-selection.webm](https://github.com/midudev/la-velada-web-oficial/assets/164126437/39171611-e9ca-4676-9b73-07d9100e43e7)

## Contexto

Debería suceder en cualquier navegador con una red lenta. 
- Navegador: Firefox, Chrome, Microsoft Edge, Brave
- Versión del navegador: ---
- Sistema operativo: Windows

**Comment by joelmh-112** [comment]
Holaa!! Estado revisando lo que describes en la PR y a mí en la web oficial no me pasa, adjunto video.

Podrías comprobar si te sigue pasando?

https://github.com/midudev/la-velada-web-oficial/assets/81626570/7cf7b140-726a-4189-9a97-f4fa2e8cf9e7

**Comment by chrisdca** [comment]
Hola @joelmh-112 que tal!. 
Actualmente las correcciones realizadas en la PR #681 que soluciona esta issue, ya fueron subidas a producción, por lo que no se podrá replicar el escenario. Puedes replicar el issue en tu **ambiente local** comentando el siguiente código en el componente SelectYourBoxer.astro

![image](https://github.com/midudev/la-velada-web-oficial/assets/164126437/e367b698-4866-4aea-beb7-c4225e5fa254)

Tener en cuenta que el issue se replica cuando la red presenta lentitud. Si tu red no presenta lentitud, puedes configurar una red más lenta desde la pestaña network de la developer tools.

![image](https://github.com/midudev/la-velada-web-oficial/assets/164126437/8fee7ebb-a393-4fd9-8628-4e14701b51b9)

**Comment by joelmh-112** [comment]
Procedo a cerrar issue ya que está solucinado!
