### ISSUE TITLE
Problema con el scroll de luchadores en la versión móvil

### ISSUE THREAD

**Issue by vicnalvin** [midudev/la-velada-web-oficial#698]
# Pre-requisitos

- [x ] Estoy corriendo la última versión.
- [x ] He revisado si ya hay un issue creado con las mismas características.

# Comportamiento esperado

Se espera que cuando se hace scroll lateral en la lista de combatientes se muestra solo la miniatura en color y el resto en blanco y negro.

También debería cambiarse al siguiente / anterior en cuanto haces un movimiento de scroll

# Comportamiento actual

si en vez de hacer scroll clicas sobre un luchador, se marca en color, no aparece arriba y no se hace un autoscroll hasta ese luchador.
También es posible mover solo un poco la lista inferior, que se active el siguiente luchador y dejar la miniatura en el anterior, por lo que no corresponde la miniatura con la imagen en grande
![photo_2024-03-20_18-46-54 (2)](https://github.com/midudev/la-velada-web-oficial/assets/74493420/8da97ca3-7eae-4f15-a828-61c238270f02)
![photo_2024-03-20_18-46-54](https://github.com/midudev/la-velada-web-oficial/assets/74493420/176957c3-f1ab-4109-b126-3a04dcfaa7f9)

# Información del bug (si corresponde)

Hacer click en un luchador que no sea el que está seleccionado en la parte central.
Mover el scroll solo un poco sin llegar a moverlo del todo al siguiente o al anterior

1. Paso 1
2. Paso 2

## Contexto

- Navegador: safari movil

**Comment by alejog-dev** [comment]
Les comparto un video demostración.

Una vez se visualiza la preview, es cuando empieza a suceder.

https://github.com/midudev/la-velada-web-oficial/assets/41591995/da17f5b4-efb0-4146-9620-4c14d61933d7

**Comment by vicnalvin** [comment]
Aquí se ve como se puede casi pasar al siguiente sin llegar a hacerlo y se carga arriba o hacer click sobre un luchador de los laterales que no se llega a cargar arriba pero si se pone a color.

https://github.com/midudev/la-velada-web-oficial/assets/74493420/222c1777-e77a-4d01-ac00-8bedfadba66e

**Comment by chermdev** [comment]
Me pasa igual con Chrome (android)
