### ISSUE TITLE
Correccion nombre de boxeador. Carreraaa

### ISSUE THREAD

**Issue by mikeOz27** [midudev/la-velada-web-oficial#699]
# Pre-requisitos

- [x] Estoy corriendo la última versión.
- [x] He revisado si ya hay un issue creado con las mismas características.

# Comportamiento esperado

![2024-03-20_13h26_47](https://github.com/midudev/la-velada-web-oficial/assets/107949089/f9d9338b-5758-4684-b3f3-fc6720f17fb7)

# Comportamiento actual

![2024-03-20_13h27_24](https://github.com/midudev/la-velada-web-oficial/assets/107949089/b7c9b7c2-9dd4-42d6-8a42-e141e94042e9)

# Información del bug (si corresponde)

No es bug, solo actualizacion de imagenes

## Pasos para reproducirlo

Descomprimir imagenes

1. Paso 1
2. Paso 2

## Contexto

- Navegador: Firefox, Chrome, Safari, Microsoft Edge, Opera, etc.
- Versión del navegador: ---
- Sistema operativo: Windows, MacOS, Linux

## Logs de error (si corresponde)

[matches.zip](https://github.com/midudev/la-velada-web-oficial/files/14670824/matches.zip)

**Comment by joelmh-112** [comment]
Ya está solucionado!!
