### ISSUE TITLE
Bug página de combates

### ISSUE THREAD

**Issue by JaimeGamm** [midudev/la-velada-web-oficial#721]
# Pre-requisitos

- [x] Estoy corriendo la última versión.
- [x] He revisado si ya hay un issue creado con las mismas características.

# Comportamiento esperado

## En la página de combates, se espera que todas las imágenes carguen al ingresar por primera vez. 

![image](https://github.com/midudev/la-velada-web-oficial/assets/58039917/7c1893b6-54b5-40f6-b19a-04117e11e59f)

# Comportamiento actual

## En la página de combate, las imágenes no cargan completamente al ingresar por primera vez. Al recargar la página, las imágenes se muestran correctamente. 

![image](https://github.com/midudev/la-velada-web-oficial/assets/58039917/c43ced63-b795-4868-8d5c-29f470ce0114)

# Información del bug (si corresponde)

## Pasos para reproducirlo

https://github.com/midudev/la-velada-web-oficial/assets/58039917/44b600c6-9192-4052-b4cc-26d1c3ac9bb3

## Contexto

- Navegador: Chrome,  movil Chrome
- Sistema operativo: Windows,  android

**Comment by midudev** [comment]
¿Se puede ver en la consola cuál es el error?

**Comment by JaimeGamm** [comment]
Hoy no pude replicar el error; podría ser un problema de rendimiento de la página. No vi ningún error en la consola ayer.
