### ISSUE TITLE
El rendimiento de la pagina es bastante malo 

### ISSUE THREAD

**Issue by salvaoo** [midudev/la-velada-web-oficial#727]
# Comportamiento esperado

Creo que debería de funcionar bien y dar la sensación de fluidez cuando accedes pero es todo lo contrario.. Antes me iba mucho más fluida.

# Comportamiento actual

https://github.com/midudev/la-velada-web-oficial/assets/18328629/f0a784a8-5bd8-4978-9ec7-63d5ce3c8241

# Información del bug (si corresponde)

Creo que quizas podria ser el light-effects de background en toda la pagina, muchas animaciones, no he adentrado en esto pero no tiene sensación de fluidez.

- Versión del navegador: --- 1.63.174 (brave). Me va igual en todos los navegadores.
- Sistema operativo: MacOS

**Comment by joelmh-112** [comment]
ostraas!! Yo no había detectado que fuese tan mal, en todos los dispositivos que he probado iba bastante bien, me podrías decir la especificaciones de tu pc solo por curiosidad? a ver si la gente se anima a hacer pruebas y poner sus specs y como les va a ellos!! Muchas gracias por ponerlo, a ver si lo podemos mejorar! 🚀

**Comment by salvaoo** [comment]
Pues tengo un macbook pro de 2018. Te dejo captura de las specs:

<img width="598" alt="image" src="https://github.com/midudev/la-velada-web-oficial/assets/18328629/5edafa89-8f4b-4785-b6a4-777dfafbbd41">

Quizas va un poco corto de gráfica pero creo que tamben es algo que se ha añadido al site porque hace unos dias lo probe y iba bien, nose que sera.. podria mirarlo este finde con mas detalle a ver si consigo encontrar que pasa o que esta causando esto y ver si le pasa a mas gente o solo a mi.

**Comment by Facug03** [comment]
Buenas, y si es algún efecto podrías correr el proyecto en local e ir quitando componentes para ver lo que es

**Comment by JLex11** [comment]
He estado investigando un poco sobre esto ya que en mi computadora tambien va algo lento y encontre en algunos foros de reddit que esto se debe a las imagenes en formato avif. Este normalmente iria fluido al renderizar avif, pero como tiene que renderizar tambien mas imagenes a la vez, a dispositivos que no tengan una grafica medianamente buena les va mal.
Igual es solo teoria y seria bueno investigarlo un poco desde este enfoque.

**Comment by joelmh-112** [comment]
A lo mejor entonces si que podrías ser por algo de AVIF y que al estar renderizando tantas pase eso... Yo investigaré un poco también a ver que encuentro. Muchas gracias gente!!!

**Comment by ElStron** [comment]
Yo he notado que el proble del lag tiene que ver con la aceleracion de hardware. Sugiero que se deberian  desactivar los efectos de fondo, cuando no se tenga soporte para la aceleracion o este desactivada.

**Comment by Facug03** [comment]
Es verdad lo que dice @ElStron, @salvaoo podrías ver si tenés esa opción desactivada en el navegador?

**Comment by midudev** [comment]
¿Puedes probar ahora y hacer otro vídeo para ver cómo va?

**Comment by salvaoo** [comment]
Ahora va muchísimo mejor! Parece que cambiaste el efecto de luces de atrás, creo que eso era lo que estaba causando el gran problema. (tengo la aceleración de hardware activada) y nose si lo de avif quizás pueda llegar a influir también.. De todas formas ahora mismo el rendimiento vuelve a ser bastante bueno por lo menos para mi 👍🏼

**Comment by joelmh-112** [comment]
Perfecto pues entonces cerramos issue! Muchas gracias por comprobarlo! 🚀
