### ISSUE TITLE
Mejora del logotipo

### ISSUE THREAD

**Issue by dserranoc** [midudev/la-velada-web-oficial#75]
En todos los assets de la velada (ya sea los que haya enseñado Ibai o los que se pueden ver en la web de 2023), el logotipo (y nombre del evento) es "La Velada Del Año", con el artículo "La" formando parte del nombre.

En el logo actual, dicho artículo no forma parte del logotipo, sino del span superior "Presentación de LA".

Creo que estaría mejor corregir dicho logo añadiendo el artículo al logo y quitándolo del span.

Además se podría añadir el isotipo (la x) detrás del texto del logotipo.

![450_1000~2.jpg](https://github.com/midudev/la-velada-web-oficial/assets/21318401/50ea6a3d-1b15-492c-9d43-8c70c448f429)

![Screenshot_2024-02-22-14-24-43-586_com.brave.browser~2.jpg](https://github.com/midudev/la-velada-web-oficial/assets/21318401/74ecf49d-ad4b-4ac5-aaeb-054fe7479a39)

**Comment by midudev** [comment]
Estamos esperando a las grafías definitivas para poder usarla. :)

**Comment by dserranoc** [comment]
> Estamos esperando a las grafías definitivas para poder usarla. :)

Perfecto, entonces no he dicho nada :D. 
Gracias Midu!
