### ISSUE TITLE
Instalar apk url error

### ISSUE THREAD

**Issue by MattEzekiel** [midudev/la-velada-web-oficial#795]
# Pre-requisitos

- [x] Estoy corriendo la última versión.
- [x] He revisado si ya hay un issue creado con las mismas características.

# Error
Al mostrar la opción para instalar la web en mi telefono aparece la url pero al final .dev en vez de .es

![Screenshot_2024-03-28-08-25-49-14_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/midudev/la-velada-web-oficial/assets/50919956/9d9a087b-b484-4bbb-8421-cedaae6d58ed)

**Comment by JLex11** [comment]
Oye no tiene que ver con que estes en el dominio .dev?
![image](https://github.com/midudev/la-velada-web-oficial/assets/93395794/e0792efb-0d19-4063-b4b6-3a1d06be2bfc)

**Comment by MattEzekiel** [comment]
Tonto de mi, si al parecer entré en dev pero no entiendo como llegué allí. Lo veo OK, cierro la Issue
