### ISSUE TITLE
Se reproduce el clip de fondo al darle a Atrás.

### ISSUE THREAD

**Issue by Jaldekoa** [midudev/la-velada-web-oficial#809]
Desde la página del boxeador, al hacer click en una declaración se reproduce el clip, Después de cerrar el vídeo, al darle a Atrás desde el navegador, no vuelve a la página anterior sino que se reproduce en segundo plano (no visible) de nuevo el vídeo ya que se oye el sonido de este.

Debería o bien recuperar el foco el vídeo o bien volver a la página principal de la selección de luchador.

- Navegador: Chrome
- Versión del navegador: 123.0.6312.58
- Sistema operativo: Ubuntu 22.04.4 LTS

**Comment by AlejandroSuero** [comment]
Creo que con la PR #810 ya se soluciona.
