### ISSUE TITLE
Boxeador Nissaxter. Error texto Xocas > Xokas

### ISSUE THREAD

**Issue by RubenJavierBachoAlarcon** [midudev/la-velada-web-oficial#826]
# Pre-requisitos

- [ ] Estoy corriendo la última versión.
- [ ] He revisado si ya hay un issue creado con las mismas características.

# Comportamiento esperado

En el apartado de la izquierda que aparecen ciertas frases la frase que contiene Xocas se escribe con 'k', es decir, Xokas

# Comportamiento actual

El texto es Xocas

# Información del bug (si corresponde)

## Pasos para reproducirlo

[1. Paso 1](https://lavelada.es/boxers/nissaxter)
2. Paso 2

## Contexto

- Navegador: Firefox, Chrome, Safari, Microsoft Edge, Opera, etc.
- Versión del navegador: ---
- Sistema operativo: Windows, MacOS, Linux

**Comment by Saguihex** [comment]
Me puedo encargar de este issue. 👍
