### ISSUE TITLE
🗓️  Error add to calendar option with microsoft 365 option

### ISSUE THREAD

**Issue by Daniel-Lagos** [midudev/la-velada-web-oficial#831]
# Comportamiento esperado

Se puede agendar el evento de la siguiente manera:

![Screenshot 2024-04-01 at 4 49 38 PM](https://github.com/midudev/la-velada-web-oficial/assets/55958214/3ab83fcf-03b1-4771-a3e9-091791522ca9)

# Comportamiento actual

Lanza un error `cannot read properties of undefined ( reading 'options')`

![Screenshot 2024-04-01 at 4 41 03 PM](https://github.com/midudev/la-velada-web-oficial/assets/55958214/1449635c-9221-466b-b141-9e79b8a63040)

---

# Información

Estuve revisando y pasa falla cuando el link es de `microsoft365`, al momento de agendar el evento lanza el error que adjunte en la imagen.

Cambié el dominio cuando viene de _microsoft365_ por el dominio de _outlook_ (en el archivo `/public/js/add-to-calendar.js)` y ya funciona bien, sin embargo, quiero saber del porqué no funciona cuando la opción viene _microsoft365_.

## Pasos para reproducirlo

1. En el home pulsar agregar al calendario
2. Seleccionar la opción de `microsoft365`.

## Contexto

No uso esa opción jajaja, la uso con `google`, pero aja, no está mal tenerlo para otras personas que sí lo usen (aclaro porque sino sale mi issue en stream y que esa opción no la usa ni el tato).

Navegador: Arc
Versión:  1.36.0 (48035)
Chromium Engine Version: 123.0.6312.87
SO: MacOS

**Comment by AlejandroSuero** [comment]
Puedes pasarme el link o el formato del link que tiene que generar?

Que estoy trabajando en esto #483 para poder hacer cambios y estilar de manera más sencilla así como hacer una carga.

**Comment by AlejandroSuero** [comment]
Es sólo cambiando microsoft365 por outlook?

**Comment by Daniel-Lagos** [comment]
Estuve investigando y el problema va más allá de la url, resulta que Microsoft cambio el enrutamiento en celular, no sé por qué, es un error que deben solucionar según lo que encontré, cambiar la url en el archivo `/public/js/add-to-calendar.js` no es tan fácil como parece, porque funciona en desktop, pero en mobile no se puede agendar.

**Comment by AlejandroSuero** [comment]
@Daniel-Lagos de momento en la PR #834 sólo llevo implementados google y outlook para escritorio.

Miraré más adelante cuando funcionen todos los de escritorio, cómo hacer los de móvil.

Que el minificado y anonimato de `add-to-calendar.js` es complejo de leer con los if raros que hace el anonimato y las variables de una letra 😅

**Comment by Daniel-Lagos** [comment]
@AlejandroSuero jajajajaj sii, minificado es supercomplejo de leer, pero ya lo tengo, voy a subir un PR con los ajustes, para que se cree la preview y me ayudes a revisar si funciona en mobile también.

**Comment by Daniel-Lagos** [comment]
@AlejandroSuero mira este PR, https://github.com/midudev/la-velada-web-oficial/pull/835 , pero los previews no se pueden ver y están fallando :c, sabes que puede ser?
