### ISSUE TITLE
Hospedar en el CDN las fuentes usadas

### ISSUE THREAD

**Issue by JLex11** [midudev/la-velada-web-oficial#838]
# Pre-requisitos

- [x] Estoy corriendo la última versión.
- [x] He revisado si ya hay un issue creado con las mismas características.

# Comportamiento esperado

Hace poco midu comento que gracias a un ataque, tuvo que hospedar en un cdn las imagenes y otros recursos. Lo que al parecer si permitio que las imagenes se mantuvieran en la cache del navegador correctamente, mejorando muchisimo la experiencia entre navegaciones.
![image](https://github.com/midudev/la-velada-web-oficial/assets/93395794/21d63712-18c8-4398-9fed-b2178fd82911)

# Comportamiento actual

Actualmente se esta usando un service worker para hacer prefetching de las fuentes y poder solventar el problema con la carga mas que todo de la fuente atomic que es algo pesada, en base al comportamiento obtuvido al hospedar en un cdn las imagenes creo que seria una buena idea **hospedar tambien las fuentes** mejorando su comportamiento en cache y la experiencia de usuario entre navegaciones aparte ya no necesitariamos el service worker por lo que evitamos problemas a futuro y carga extra de javascript.
![image](https://github.com/midudev/la-velada-web-oficial/assets/93395794/e2f6c0fc-a03c-417a-96a4-25c85b4996cb)

**Comment by JosenRomero** [comment]
Ya se ha agregado un commit sobre está issue: [Use CDN for font ](https://github.com/midudev/la-velada-web-oficial/commit/8d49c75754e363bb2f17ead3661e4b6c3a872148)
