### ISSUE TITLE
Error en responsive

### ISSUE THREAD

**Issue by jsebasmuller** [midudev/la-velada-web-oficial#84]
El responsive no se ve bien en el dispositivo POCO F3
![Screenshot_2024-02-22-12-21-27-178_com android chrome](https://github.com/midudev/la-velada-web-oficial/assets/65184492/ede070f8-314c-474b-858b-33eb30b9573f)

**Comment by FabianMontoya** [comment]
Seria bueno que dejaras que tipo de resolución tienes o que resolución está tomando la página web en tu dispositivo, eso puede dar un poco la idea del problema

**Comment by AgusjkDev** [comment]
¿Es posible que tengas modo desktop activado en las configuraciones?

**Comment by jsebasmuller** [comment]
No, no tengo activado el modo escritorio

**Comment by jsebasmuller** [comment]
> ¿Es posible que tengas modo desktop activado en las configuraciones?
No, no tengo activado el modo escritorio

**Comment by jsebasmuller** [comment]
> ¿Es posible que tengas modo desktop activado en las configuraciones?

No, no tengo activado el modo escritorio

**Comment by maag070208** [comment]
Revisando el codigo, mire que la imagen que esta dentro de este contenedor es la que esta causando el issue de el responsive.

![image](https://github.com/midudev/la-velada-web-oficial/assets/48636949/1678614b-edd8-45a5-86fb-ae8cf47e454d)

El motivo es el siguiente.
<img width="815" alt="image" src="https://github.com/midudev/la-velada-web-oficial/assets/48636949/8aa6b6db-c0cb-42eb-8c7d-b9f867ff35f3">

En este bloque de codigo, el contenedor esta tomando el 100%, causando que la imagen que esta dentro tome ese mismo ancho.

Ahora, no se, si eliminar ese bloque o si de aplicarle al contenedor un display: initial; para que no exceda el ancho.

**Comment by seobryn** [comment]
Estoy revisando en este momento y no se presenta el error en responsive, probado en Brave:

![localhost_4321_](https://github.com/midudev/la-velada-web-oficial/assets/3819912/e828fd51-c6f7-4dc7-af38-1bacd74ca839)

**Comment by jsebasmuller** [comment]
> Estoy revisando en este momento y no se presenta el error en responsive, probado en Brave:
> 
> ![localhost_4321_](https://private-user-images.githubusercontent.com/3819912/307449473-e828fd51-c6f7-4dc7-af38-1bacd74ca839.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MjM3MjYsIm5iZiI6MTcwODcyMzQyNiwicGF0aCI6Ii8zODE5OTEyLzMwNzQ0OTQ3My1lODI4ZmQ1MS1jNmY3LTRkYzctYWYzOC0xYmFjZDc0Y2E4MzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjNUMjEyMzQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTQ2ODI2OGQwMjE3Y2JkZjFmMDRiNGQ0Y2ZhZjY4NmJmYzNlN2ZlZjY2NzNjN2ZhMGViMjAwMDMyMTc0Y2Q4ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RJcx5XyPiGc0v-Kqbos4WZ6SYxRvEPKdtpZaljuQsg0)

Así es ya se resolvio, procedo a cerrarlo
