### ISSUE TITLE
Reporte de error: Video de entrenamiento de Skain bloqueado

### ISSUE THREAD

**Issue by JaimeGamm** [midudev/la-velada-web-oficial#841]
# Pre-requisitos

- [x] Estoy corriendo la última versión.
- [x] He revisado si ya hay un issue creado con las mismas características.

# Comportamiento actual

El video de entrenamiento de Skain se encuentra bloqueado y no se puede reproducir en la plataforma. Al intentar acceder al video, se muestra un mensaje indicando que el contenido ha sido bloqueado por LatinAutor - UMPG.

![image](https://github.com/midudev/la-velada-web-oficial/assets/58039917/3c520136-368b-4aaf-b7c6-e20a6fddc086)

**Comment by ediergama** [comment]
oh baia, ya se había cambiado otro vídeo por el mismo error, estuve revisando y creo que todos los que ha subido de entrenamiento tienen Copy, ta complicao xD

**Comment by JaimeGamm** [comment]
Es el único video que me muestra el error de copyright, los otros se reproducen correctamente.

**Comment by AlejandroSuero** [comment]
@JaimeGamm, @ediergama a mí no me sale bloqueado, quizás es por verlo desde España.

Si podéis comprobarlo usando alguna VPN para ver si es ese el problema.

<img width="1657" alt="Screenshot 2024-04-03 at 01 28 22" src="https://github.com/midudev/la-velada-web-oficial/assets/71392160/4b28b1eb-1329-436e-bcd9-90473ad3147d">

**Comment by JaimeGamm** [comment]
yo soy de colombia, pero con vpn me funciona 
![image](https://github.com/midudev/la-velada-web-oficial/assets/58039917/793e8ce1-24db-4e7b-867e-0c587bdb1b63)
el  bloqueo de copyright  debe se para latinoamerica

**Comment by AlejandroSuero** [comment]
Pues entonces es que está bloqueado por región.

Lo que se podría es intentar buscar qué vídeos están bloqueados y en cambiar el link dependiendo de la región. Así si por ejemplo, bloquea el del primer entrenamiento, al menos hay un vídeo a reproducir.

@JaimeGamm, @ediergama, @midudev

**Comment by AlejandroSuero** [comment]
Este lo bloquea? https://www.youtube.com/watch?v=Kpq377WVbtA
