### ISSUE TITLE
Incompatibilidad con Safari

### ISSUE THREAD

**Issue by Herna1994** [midudev/la-velada-web-oficial#848]
# Pre-requisitos

- Estoy corriendo la última versión en macOS Sonoma 14.4

# Comportamiento esperado

Debería hacer el view-transition, y en caso de que Safari no lo soporte al menos mostrar el vídeo.

# Comportamiento actual

No se ve la view-transition ni el vídeo de fondo.

## Pasos para reproducirlo

1. Abir lavelada.es en Safari

## Contexto

- Navegador: Safari
- Versión del navegador: 17.4
- Sistema operativo: macOS

**Comment by AlejandroSuero** [comment]
Sólo es el https://lavelada.es/combates/[id] ?

**Comment by AlejandroSuero** [comment]
<img width="817" alt="Screenshot 2024-04-04 at 02 06 25" src="https://github.com/midudev/la-velada-web-oficial/assets/71392160/1057e3a9-1afc-4e09-ae79-c822994be03f">

@Herna1994 A mí me funciona ya, comprueba a ver si va.

**Comment by AlejandroSuero** [comment]
<img width="804" alt="Screenshot 2024-04-04 at 02 14 53" src="https://github.com/midudev/la-velada-web-oficial/assets/71392160/2e19354b-8a3e-4a3e-85bd-1c7374e59440">

Tampoco cargan las fuentes

**Comment by AlejandroSuero** [comment]
Carga inicial:

<img width="804" alt="Carga de datos sin los vídeos" src="https://github.com/midudev/la-velada-web-oficial/assets/71392160/f86024b3-bf09-40d3-a6e0-94b3c5eae0f0">

Recargando la página:

https://github.com/midudev/la-velada-web-oficial/assets/71392160/1a18f4fe-7158-43c5-a63b-f6e61478fe21

**Comment by AlejandroSuero** [comment]
Creo que ya he encontrado una solución @Herna1994 , ahora tras comprobar en los demás navegadores, hago una PR.

**Comment by AlejandroSuero** [comment]
@Herna1994 ya está la PR hecha si quieres comprobar los cambios puedes hacer fork de mi [repo](https://github.com/AlejandroSuero/la-velada-web-oficial) y probar la rama [feature/fix-safari-combat-video-not-playing](https://github.com/AlejandroSuero/la-velada-web-oficial/tree/feature/fix-safari-combat-video-not-playing)

**Comment by AlejandroSuero** [comment]
@Herna1994 ya se puede cerrar esta issue con #849 mergeada.
