### ISSUE TITLE
Combat hover alt text is not descriptive

### ISSUE THREAD

**Issue by Saguihex** [midudev/la-velada-web-oficial#852]
- [X] Estoy corriendo la última versión.
- [X] He revisado si ya hay un issue creado con las mismas características.

# Comportamiento esperado

El texto alternativo de las imágenes de los combates es más descriptivo.

# Comportamiento actual

El texto alternativo de las imágenes de los combates solo se diferencian en el número del combate.

# Información del bug (si corresponde)

El texto alternativo de las imágenes no aporta información descriptiva sobre cuál es cada combate.
Debería incluir los nombres de los boxeadores; con posible caso especial del Rey de la pista, ya que podría ser demasiado largo. Aunque cualquier otra idea es bienvenida.

![CombatHover](https://github.com/midudev/la-velada-web-oficial/assets/64600021/6a08d592-b90a-43e5-9d97-4bcef8f4b6e2)

## Pasos para reproducirlo

1. Acceder a https://lavelada.es/combates
2. Hacer hover en las imágenes de los combates

## Contexto

- Navegador: Microsoft Edge (123.0.2420.65) y Google Chrome (123.0.6312.86)
- Sistema operativo: Windows

**Comment by Saguihex** [comment]
@AlejandroSuero Lo veo mucho mejor que antes. Aunque que te parece algo como esto? Cuidado que me quita las tildes 😩
title={`Ir al combate ${combatData.number}: ${formattedCombats}`} 

Creo que ya se sobreentiende que son "de la Velada IV" 😄

**Comment by AlejandroSuero** [comment]
@Saguihex ya he hecho el cambio.

**Comment by Saguihex** [comment]
@AlejandroSuero lo veo perfecto 👍
