### ISSUE TITLE
Falta separador/nexo entre los participantes del 2vs2 en Pronósticos

### ISSUE THREAD

**Issue by Saguihex** [midudev/la-velada-web-oficial#853]
# Pre-requisitos

Acceso a una cuenta de Twitch.

- [X] Estoy corriendo la última versión.
- [X] He revisado si ya hay un issue creado con las mismas características.

# Comportamiento esperado

El texto de los pronósticos del 2vs2 tiene gramática apropiada.

# Comportamiento actual

El texto de los pronósticos del 2vs2 no tiene ningún separador entre los participantes de los equipos.

![Vote2vs2_1](https://github.com/midudev/la-velada-web-oficial/assets/64600021/fc4ef649-c040-466b-959d-adf8e7616a48)
![Vote2vs2_2](https://github.com/midudev/la-velada-web-oficial/assets/64600021/2f2a10d9-def4-4c2a-b453-8a5760082576)

# Información del bug (si corresponde)

En la página de pronósticos, los textos al hacer hover en los equipos del 2vs2, carecen de un nexo entre los participantes como "y".

## Pasos para reproducirlo

1. Acceder a https://lavelada.es/pronosticos
2. Iniciar sesión con Twitch
3. Hacer hover en los equipos del 2vs2.

## Contexto

- Navegador: Microsoft Edge (123.0.2420.65) y Google Chrome (123.0.6312.86)
- Sistema operativo: Windows

**Comment by AlejandroSuero** [comment]
@midudev habría que cambiar la imagen? O se hace una PR para cambiarlo a como están los de **Rey de la Pista* (con texto)?

**Comment by Saguihex** [comment]
@AlejandroSuero Lo que mencioné ya son textos. Perdona si no me expliqué bien. 😅

**Comment by AlejandroSuero** [comment]
@Saguihex ya he añadido el separador, a ver que te parece.

**Comment by Saguihex** [comment]
@AlejandroSuero lo veo genial en las imágenes de la PR (no sé como verlo en local 😅)
