### ISSUE TITLE
Propuesta: Agregar el podcast de Luzu(? EL PODCAST PIRATA DE LA VELADA DEL AÑO 4

### ISSUE THREAD

**Issue by MattEzekiel** [midudev/la-velada-web-oficial#859]
# Pre-requisitos

- [x] Estoy corriendo la última versión.
- [x] He revisado si ya hay un issue creado con las mismas características.

## Propuesta

El 4 de abril Ibai subió un video hablando sobre el podcast de Luzu como "nuevo director de la velada", no sé si es joda/coña o qué, pero si es cierto, se podría agregar a la web

### Video
<div align="center">

https://github.com/midudev/la-velada-web-oficial/assets/50919956/a1bf313e-b611-4615-ba34-c5868ecf06ce

</div>

**Comment by zackproject** [comment]
En los primeros segundos del primer capitulo ya dice que es "no oficial". Aunque es un buen contenido, la web de la velada es "oficial". Yo creo que si en algún momento se hace "El podcast oficial de la velada" se podría añadir, de momento no.
Podcast: [ASÍ VEO LA VELADA DEL AÑO 4 - E1](https://youtu.be/gpPX_U_SpD0?si=NFnluWkhkfG02vb2)

**Comment by MattEzekiel** [comment]
@zackproject si, vi que dice que no es oficial, pero fue antes de ese streaming o del video con Ibai, no sé si eso haya cambiado

**Comment by midudev** [comment]
Al no ser oficial, vamos a evitar añadirlo.
