### ISSUE TITLE
Sugerencia: Poder acceder al perfil de la aliada desde el perfil del luchador en el 2vs2

### ISSUE THREAD

**Issue by Saguihex** [midudev/la-velada-web-oficial#864]
- [X] Estoy corriendo la última versión.
- [X] He revisado si ya hay un issue creado con las mismas características.

# Comportamiento esperado

Mostrar y poder acceder al perfil de la aliada en el perfil del luchador.

# Comportamiento actual

No se muestra ni se puede acceder al perfil de la aliada en el perfil del luchador.

# Información del bug (si corresponde)

Para poder acceder al perfil de la aliada, es necesario acceder al perfil de una de las rivales y luego al perfil de la aliada.
Sería más directo si se puede acceder directamente con un solo clic, además de incluir información relevante en el perfil.

![Aliada](https://github.com/midudev/la-velada-web-oficial/assets/64600021/fa899f87-16d4-4452-8429-af51b62a919a)

## Pasos para reproducirlo

1. Acceder a la página de la velada
2. Ir al perfil de cualquiera de las luchadoras del 2vs2

## Contexto

- Navegador: Microsoft Edge (123.0.2420.65) y Google Chrome (123.0.6312.86)
- Sistema operativo: Windows

**Comment by AlejandroSuero** [comment]
He estado haciendo esto a ver que te parece @Saguihex

Poniendo un componente similar a la derecha:
<img width="1029" alt="Screenshot 2024-04-05 at 18 19 57" src="https://github.com/midudev/la-velada-web-oficial/assets/71392160/41fc7b4b-e9ff-45ac-af43-e380bd7b0079">

> Sin agregar nada más.

Poniendo un componente similar encima del de rivales:
<img width="1029" alt="Screenshot 2024-04-05 at 18 20 39" src="https://github.com/midudev/la-velada-web-oficial/assets/71392160/b98cb9f7-df4d-4059-9cc9-e693d912411b">

> Cambiando `gap-y-20` a `gap-y-5`.

Añadiendo un componente similar superpuesto al de rivales:
<img width="1029" alt="Screenshot 2024-04-05 at 18 32 55" src="https://github.com/midudev/la-velada-web-oficial/assets/71392160/5861e576-e957-47af-9008-f5ae7d087879">

> `relative` en el de rivales, `absolute` en el de aliadas.

**Comment by Saguihex** [comment]
@AlejandroSuero En mi opinión (no soy experto en la materia):
1. No me convence que los componentes de "rivales" y "aliada" estén en distintas alturas.
2. Era lo que tenía pensado. Pero al tener algunas de las boxeadoras 3 citas, la columna de la izquierda tiene mucho más peso.
3. Es la que mejor queda y rellena el hueco que quedaba libre.

**Comment by AlejandroSuero** [comment]
@Saguihex voy a intentar luego y sino mañana a hacerlo cambiando en donde se muestran los rivales. Para que quede algo como:

```text
 _______________________
| cita1 img img dato1  |
| cita2 img img dato2  |
| cita3 img img dato3  |
|        nombre        |
| rival         ally   |
|______________________|
```

Para que así quede alineado independientemente del número de citas. Y ajustarlo al diseño de móvil.

**Comment by AlejandroSuero** [comment]
@Saguihex he hecho una PR con los cambios, solo faltaría ajustar al diseño en `mobile`.
