### ISSUE TITLE
Video background en sección combate solo se reproduce la primera vez

### ISSUE THREAD

**Issue by lucas-labs** [midudev/la-velada-web-oficial#865]
# Comportamiento esperado

Siempre debería reproducirse el video de background en las secciones de combate.

# Comportamiento actual

El video de background en la sección de combates se reproduce para el primer combate, pero si vamos para atrás y pinchamos en otro combate, ya no se reproduce el video.

## Pasos para reproducirlo

https://github.com/midudev/la-velada-web-oficial/assets/12949236/b3379f3c-973d-454c-85d5-0612eb66daa4

## Contexto

- Navegador: Chrome, Edge y Arc
- Versión del navegador: latest en los 3
- Sistema operativo: Windows

**Comment by AlejandroSuero** [comment]
@lucas-labs con esto #866 ya se soluciona, que era un bug por no tener `autoplay`.

https://github.com/midudev/la-velada-web-oficial/assets/71392160/f5656375-929f-48ba-8f28-8bc57896c250

> En el último vuelvo atrás usando el navegador como en tu vídeo
> para demostrar que también funciona de esa manera.

**Comment by AlejandroSuero** [comment]
En Safari sigue estando el problema.

https://github.com/midudev/la-velada-web-oficial/assets/71392160/e2b5031c-21c8-42be-87e1-6ba475afdaec

Si alguien sabe cómo solucionarlo, que me diga o haga una PR y la linkee aquí.

**Comment by PmplCode** [comment]
Buenas, prueba a poner los siguientes atributos al tag de video: `autoplay loop muted playsinline`

**Comment by AlejandroSuero** [comment]
@PmplCode ya está hecho en #866
