### ISSUE TITLE
página no responde en la sección de boxeadores (Alana) y deja de funcionar el carrusel

### ISSUE THREAD

**Issue by MiltonMora** [midudev/la-velada-web-oficial#867]
Cuando ingreso a la página desde mi móvil android y seleccionó a (Alana), no funcionan algunas partes, cómo las citas y el menú, al volver hacia atrás ya no funciona el carrusel.

https://github.com/midudev/la-velada-web-oficial/assets/45776823/4b3622e5-d1c5-4de5-9cea-e0f37f914e82

**Comment by AlejandroSuero** [comment]
Desde mi Android (Redmi Note 8 Pro) tampoco funciona.

Usando Safari desde iOS (simulador):

https://github.com/midudev/la-velada-web-oficial/assets/71392160/e9a53ec7-b702-4661-bda6-3e7da48dd520

Usando Android (simulador):

https://github.com/midudev/la-velada-web-oficial/assets/71392160/4fbad084-fbb7-42ff-a73b-116b03111e55

**Comment by AlejandroSuero** [comment]
Si recargas la página o cambias de luchadora te funcionan las citas de Alana @MiltonMora?

https://github.com/midudev/la-velada-web-oficial/assets/71392160/1f72be73-a9ea-4246-88a0-6c6fa98cf478

> PD: El resto, menú y carrusel, me funcionan correctamente aún volviendo hacia atrás.

**Comment by MiltonMora** [comment]
> Si recargas la página o cambias de luchadora te funcionan las citas de Alana @MiltonMora?
> 
>  alana-quotes-in-android-phne.mp4 
> > PD: El resto, menú y carrusel, me funcionan correctamente aún volviendo hacia atrás.

Si, recargando la página funciona
