### ISSUE TITLE
no levanta el proyecto local

### ISSUE THREAD

**Issue by jccampos2007** [midudev/la-velada-web-oficial#870]
# Pre-requisitos

- [ x] Estoy corriendo la última versión.
- [ x] He revisado si ya hay un issue creado con las mismas características.

# Comportamiento esperado

al darle *pnpm rum dev*, ver el proyecto local

# Comportamiento actual

arroja el siguente error de tyscript "checkAllowed is not a function"

# Información del bug (si corresponde)

![Captura de pantalla de 2024-04-06 15-22-13](https://github.com/midudev/la-velada-web-oficial/assets/19821666/4c37c0dc-9852-4e69-8229-f7872af38497)

## Pasos para reproducirlo

clone
instale dependencia
levantar el proyecto local

## Contexto

instale y configure version de node, nvm, segun sugerencias

- Navegador: Firefox, Chrome, Safari, Microsoft Edge, Opera, etc.
- Versión del navegador: ---
- Sistema operativo: Windows, MacOS, Linux

**Comment by CoffeSiberian** [comment]
Me paso exactamente lo mismo, si no te molesta de momento puedes forzar un `true` a la siguiente constante y poder trabajar mientras lo arreglan (algunos assets posiblemente no carguen)

![imagen](https://github.com/midudev/la-velada-web-oficial/assets/61036343/0bc8c5ee-2ef8-44c6-8b34-555318219d85)

**Comment by midudev** [comment]
Ya debería funcionar 👍
