### ISSUE TITLE
Seguridad: Deshabilitar soporte para TLSv1.0 y TLSv1.1

### ISSUE THREAD

**Issue by alesnav** [midudev/la-velada-web-oficial#881]
# Pre-requisitos

- [ x ] Estoy corriendo la última versión.
- [ x ] He revisado si ya hay un issue creado con las mismas características.

# Comportamiento esperado

Página soportando únicamente protocolos seguros sobre HTTPS.

# Comportamiento actual

Actualmente, la página web soporta protocolos TLSv1.0 y TLSv1.1, considerados vulnerables.

# Información del bug (si corresponde)

## Pasos para reproducirlo

Basta comprobarlo de forma simple mediante SSL Labs:
https://www.ssllabs.com/ssltest/analyze.html?d=lavelada.es&latest

## Contexto

Indiferente.

## Logs de error (si corresponde)

No necesarios.

**Comment by midudev** [comment]
Hecho!
