### ISSUE TITLE
No deja realizar el pronóstico si se usa uBlock

### ISSUE THREAD

**Issue by byMagg** [midudev/la-velada-web-oficial#887]
# Pre-requisitos

- [ ] Estoy corriendo la última versión.
- [x] He revisado si ya hay un issue creado con las mismas características.

# Comportamiento esperado

Se debería poder realizar los votos correctamente aún usando un bloqueador de contenidos

# Comportamiento actual

No permite realizar el voto, hago click en el boxeador en concreto y simplemente no se obtiene ningún feedback y en la consola se puede ver un bloqueo que hace mi bloqueador de contenidos (uBlock)

![image](https://github.com/midudev/la-velada-web-oficial/assets/44727429/23f26cab-e9b4-493a-ae02-82dc9b72d4f7)

# Información del bug (si corresponde)

## Pasos para reproducirlo

1. Paso 1, descargar uBlock
2. Paso 2, realizar un voto en la web

## Contexto

- Navegador: Chrome
- Versión del navegador: 123.0.6312.106
- Sistema operativo: Windows

## Logs de error (si corresponde)

![image](https://github.com/midudev/la-velada-web-oficial/assets/44727429/e92882ac-c619-482a-874b-6b661dd86aef)

**Comment by midudev** [comment]
El error no es exactamente este ya que el script que se ve bloqueado no tiene nada que ver con las votaciones.
