### ISSUE TITLE
No deja iniciar sesion para votar

### ISSUE THREAD

**Issue by RafaMojica** [midudev/la-velada-web-oficial#888]
# Pre-requisitos

- [x] Estoy corriendo la última versión.
- [x] He revisado si ya hay un issue creado con las mismas características.

# Comportamiento esperado

Al darle cick al botton de iniciar seccion para reaizar pronostico poder iniciar seccion para poder votar 

# Comportamiento actual

No deja iniciar sesion para votar, la pagina no realiza ninguna accion al votar

# Información del bug (si corresponde)

Me di cuenta que al actualizar la vista "https://lavelada.es/pronosticos", me deja iniciar sesion, sali de la pagina y volvi a entrar y no funciona hasta que actualice la pestaña, Ahi deje un video y abri tambien la consola. 

## Pasos para reproducirlo

1. Ingresar a la pagina
2. ir al la pestaña https://lavelada.es/pronosticos
3. darle click al boton de "Iniciar session para participar"
4. No pasa nada

## Contexto

- Navegador: Chrome
- Versión del navegador: Versión 123.0.6312.105 (Build oficial) (64 bits)
- Sistema operativo: Windows, Linux

## Logs de error (si corresponde)

[Grabación de pantalla desde 2024-04-11 13-10-38.webm](https://github.com/midudev/la-velada-web-oficial/assets/90728588/f7d45102-2632-4797-affa-d1aedce99a90)

**Comment by AlejandroSuero** [comment]
@RafaMojica a mi me deja iniciar sesión pero no registrar el voto.

**Comment by AlejandroSuero** [comment]
@RafaMojica ya me funciona, prueba a ver si ya te funciona a ti también.

**Comment by RafaMojica** [comment]
Aun me toca actualizar el navegador para entrar

**Comment by pjmartorell** [comment]
Hay un warning en tu consola que menciona una extension del navegador. Mira si hay alguna extension que esté interfiriendo con la web.
