### ISSUE TITLE
No deja votar si no entras directo desde la página pronosticos

### ISSUE THREAD

**Issue by Facug03** [midudev/la-velada-web-oficial#899]
# Pre-requisitos

- [x] Estoy corriendo la última versión.
- [x] He revisado si ya hay un issue creado con las mismas características.

# Comportamiento esperado

Que la parte de pronósticos funcione correctamente.

# Comportamiento actual

Cuando entro desde el inicio a la página pronósticos no funciona, pero si hago F5 funciona. Probé en local y esto no pasa.

## Pasos para reproducirlo

https://github.com/midudev/la-velada-web-oficial/assets/107658697/f0bd1f25-a831-4aa9-8279-1484c10614e0

## Contexto

- Navegador: Firefox (También lo probé en Edge)
- Versión del navegador: 124.0.2 (64-bit)
- Sistema operativo: Windows

**Comment by Facug03** [comment]
También probé desactivando AdBlock pero igual no funciona.

**Comment by rubeneitor21** [comment]
En opera gx (core: 107.0.5045.86) solo deja entrar si desactivas adblock y bloqueador de trackers

**Comment by yurigo** [comment]
Creo que el comportamiento lo está causando el prefetch. El script que habilita el voto cuando viene de una precarga no se ejecuta y por eso deja de funcionar.

**Comment by yurigo** [comment]
Hay otras issues que comentan que no funciona un evento/click pero sí funcionan al recargar:

- https://github.com/midudev/la-velada-web-oficial/issues/867
- https://github.com/midudev/la-velada-web-oficial/issues/887
- https://github.com/midudev/la-velada-web-oficial/issues/888

  Tiene números que se trate del mismo comportamiento.

**Comment by Facug03** [comment]
Por lo que pude leer en esta issue que tiene los mismos problemas https://github.com/withastro/astro/issues/9684, es un problema de Cloudflare y se arregla asi:

![imagen](https://github.com/midudev/la-velada-web-oficial/assets/107658697/c80624b6-b65b-45e4-af7b-704c0446d4f1)

**Comment by Facug03** [comment]
Desactivando eso se tendría que solucionar, pero la verdad no sé si la optimización empeora o no cambia nada si se desactiva eso o si siquiera está activado

![imagen](https://github.com/midudev/la-velada-web-oficial/assets/107658697/d3a3d7b5-e94b-47c2-ac86-ba4cfa29664f)

**Comment by midudev** [comment]
Desactivado Rocket Loader y parece que ya no da problemas!
