### ISSUE TITLE
Sugerencia: Agregar Rate Limit de Cloudflare a los recursos estáticos del CDN

### ISSUE THREAD

**Issue by fernandodilland** [midudev/la-velada-web-oficial#900]
# Pre-requisitos

- [x] Estoy corriendo la última versión.
- [x] He revisado si ya hay un issue creado con las mismas características.

# Comportamiento esperado

Se espera que tenga activada la regla de rate limit a los recursos del CDN que están en el dominio cdn.lavelada.dev (ejemplo: [https://cdn.lavelada.dev/boxers/el-mariana-big.webp](https://cdn.lavelada.dev/boxers/el-mariana-big.webp)), ya que no tiene rate limit como la página principal, si se hace un ataque DDoS, no se va a caer, pero si excederá el free tier del R2 de Cloudflare.

# Comportamiento actual

Al actualizar varias veces los recursos estáticos de manera independiente, no se identifica rate limit.

## Pasos para reproducirlo

1. Ingrese a cualquier estático (imágenes por ejemplo) de la página web.
2. Actualice constantemente usando "F5".
3. Compruebe usted mismo que no tiene activado el rate limit, a diferencia de la página principal.

**Comment by fernandodilland** [comment]
@midudev

**Comment by midudev** [comment]
No hay que preocuparse y lo hemos explicado en directo en Twitch.
