### ISSUE TITLE
Sección de combates incompleta

### ISSUE THREAD

**Issue by 100451296** [midudev/la-velada-web-oficial#905]
# Comportamiento actual

En la sección de combates, falta la información detallada de cada boxeador del rey de la pista. Tampoco se ofrece una forma de comparar boxeadores como en el resto de combates.

![Captura desde 2024-04-15 15-37-07](https://github.com/midudev/la-velada-web-oficial/assets/98945796/98cd95ef-0785-4333-8d45-7ece2b9a4285)

**Comment by EduWTR** [comment]
Hola! Se sabe como irán las peleas? hay llaves? 

Puedo tirar una idea? 
![image](https://github.com/midudev/la-velada-web-oficial/assets/139919492/270d7db0-1c99-4d7c-8783-5e3ec6fe6428)

o de ambos lados y al centro el 'rey de la pista' ( estilo champions/mundial de futbol )

**Comment by EduWTR** [comment]
El día antes del evento se hara pesaje ,y se decide el orden que saldrán los peleadores.

1vs1, Peleas de 1 min. Ganador queda en el ring. Sin descansar. 

Sólo puede descansar si hay KO / TKO / descalificación por referee, en el tiempo sobrante de ese minuto.

Boxeador knockeado queda eliminado del torneo.

No terminé de entender cómo ganan, supongo que el que más peleas gane.
