### ISSUE TITLE
Error invalid URL

### ISSUE THREAD

**Issue by MattEzekiel** [midudev/la-velada-web-oficial#912]
# Pre-requisitos

- [x] Estoy corriendo la última versión.
- [x] He revisado si ya hay un issue creado con las mismas características.

# Error
![image](https://github.com/midudev/la-velada-web-oficial/assets/50919956/050a143e-e134-45ab-9704-2a8114d8dcab)

# Información del bug (si corresponde)

## Pasos para reproducirlo

arrancar el proyecto

**Comment by AlejandroSuero** [comment]
@MattEzekiel así?

https://github.com/midudev/la-velada-web-oficial/assets/71392160/43fa2258-91a9-4f56-8dd6-aa89926034b0

**Comment by MattEzekiel** [comment]
@AlejandroSuero El error me lo da el canonical

https://github.com/midudev/la-velada-web-oficial/assets/50919956/4fd0dccf-cda0-4d42-ae99-94dec44de19b

**Comment by AlejandroSuero** [comment]
@MattEzekiel cuando uso firefox developer edition, tampoco me da ese fallo.

Y el *canonical* me aparece así `<link rel="canonical" href="https://lavelada.es/">`

https://github.com/midudev/la-velada-web-oficial/assets/71392160/2e6db7ad-c41c-44d4-aacf-0299e8f4a35f

Si lo hago el siguiente cambio en `src/pages/index.astro`, el **canonical** pasa a ser `<link rel="canonical" href="http://localhost:4321/">`

Antes del cambio:
<img width="1654" alt="Screenshot 2024-04-18 at 17 58 14" src="https://github.com/midudev/la-velada-web-oficial/assets/71392160/2b291340-d707-49fa-b2ba-67b3ce5d7c05">

Después:
<img width="1654" alt="Screenshot 2024-04-18 at 17 58 06" src="https://github.com/midudev/la-velada-web-oficial/assets/71392160/ab358b9e-6738-4f0d-9bd0-089c45ee80a6">
