### ISSUE TITLE
E NOTADO QUE EN CHROME HACE UN PARPADEO AL MOMENTO DE PASAR LAS IMAGENES SE VE RARO

### ISSUE THREAD

**Issue by DruChill** [midudev/la-velada-web-oficial#918]
# Pre-requisitos

- [x] Estoy corriendo la última versión.
- [x] He revisado si ya hay un issue creado con las mismas características.

# Comportamiento esperado

Que no parpadee no? algo asi:
![Captura de pantalla 2024-04-20 a la(s) 10 34 09 a  m](https://github.com/midudev/la-velada-web-oficial/assets/116127836/403421ea-75c8-4875-b04a-c34ef3b9630a)

# Comportamiento actual

El problema es que cada vez que das click siguiente ya sea con el mouse o el teclado brilla la imagen de esta manera es difícil tomar captura:
![Captura de pantalla 2024-04-20 a la(s) 10 33 14 a  m](https://github.com/midudev/la-velada-web-oficial/assets/116127836/c3b6a1c1-1f6e-49a4-bd59-b625a37c2290)

## Pasos para reproducirlo

1. Paso 1 cualquier bóxers esta en todos el efecto parpadeante https://lavelada.es/boxers/alana
2. Paso 2 ubicarte en el carrusel justo donde que se vea esta imagen:
![Captura de pantalla 2024-04-20 a la(s) 11 33 49 a  m](https://github.com/midudev/la-velada-web-oficial/assets/116127836/ad729ccf-501d-4ae8-a50f-9015d69753d7)

## Contexto
Esta es mi version de chrome la más reciente:
en safari funciona bien!

- Navegador: Chrome
- Versión del navegador: Versión 124.0.6367.62 (Build oficial) (arm64)
- Sistema operativo: MacOS - Sonoma

## Logs de error (si corresponde)

![Captura de pantalla 2024-04-20 a la(s) 11 38 02 a  m](https://github.com/midudev/la-velada-web-oficial/assets/116127836/8578aeb9-b91a-4475-bb0a-2c3b05008bf3)

**Comment by AlejandroSuero** [comment]
@DruChill he arreglado el parpadeo en la PR #961, se debía al uso de [View Transitions](https://docs.astro.build/en/guides/view-transitions/) ya que añadía la transición y tanto esa imagen como la del/la boxeador/a en cuestión también se veían afectadas.
