### ISSUE TITLE
Remover warnings al momento de instalar las dependencias de node

### ISSUE THREAD

**Issue by Jesus-Rojas** [midudev/la-velada-web-oficial#922]
## Descripción

Al momento de instalar las dependencias del proyecto, me estaba arrojando unos warnings. Al iniciar el proyecto se empezó con la versión de node `18.14.1`

## Capturas de pantalla (si corresponde)

https://github.com/midudev/la-velada-web-oficial/assets/57029059/413147d2-6c66-4240-987d-c3f834500d17

**Comment by AlejandroSuero** [comment]
@Jesus-Rojas salen warnings si haces `nvm install 18` y `nvm use 18`? En teoría, con eso instala la última estable de la v18.
