### ISSUE TITLE
Fix: El Mariana imagen de combate

### ISSUE THREAD

**Issue by nescalada** [midudev/la-velada-web-oficial#927]
# Comportamiento esperado

El Mariana no es Quico en la sección de Combates.

[imagen actual, a reemplazar] [WEBP 95KB]
https://cdn.lavelada.dev/boxers/vote/vote-6-el-mariana.webp

[imagen propuesta, adjunta] [WEBP 95KB]
[vote-6-el-mariana.zip](https://github.com/midudev/la-velada-web-oficial/files/15095139/vote-6-el-mariana.zip)

# Actual vs. Propuesta

<img height="260" alt="image" src="https://github.com/midudev/la-velada-web-oficial/assets/7088028/e1ac32a0-88fd-4cde-85c5-21a829ef3eb5"> <img height="260" alt="image" src="https://github.com/midudev/la-velada-web-oficial/assets/7088028/3cf61fd3-6112-4d2b-8fa4-f79f43f88a8c">

# Imagen de Quico para referencia:

<img height="260" alt="image" src="https://github.com/midudev/la-velada-web-oficial/assets/7088028/48159f60-9fac-4670-87d8-5ab8ba1ae5da">

**Comment by fernandodilland** [comment]
La deformación por el vidrio, persiste en la parte superior (por encima de la ceja).

**Comment by midudev** [comment]
jajajaja gracias!
