### ISSUE TITLE
[Bug]: Error al votar zeling y nissaxter

### ISSUE THREAD

**Issue by jBenitoLopez** [midudev/la-velada-web-oficial#951]
### Señala los requisitos cumplidos

- [X] Estoy corriendo la última versión.
- [X] He revisado si ya hay un issue creado con características similares.

### Comportamiento actual

![2024-05-08 14_09_10-Pronostica los ganadores - La Velada del Año IV - Opera](https://github.com/midudev/la-velada-web-oficial/assets/107802557/c6c12195-87f7-450a-ba09-504ceab485d0)

![2024-05-08 14_16_44-Pronostica los ganadores - La Velada del Año IV - Opera](https://github.com/midudev/la-velada-web-oficial/assets/107802557/c0f04f69-e5a8-4996-b0dc-87fcd912e642)

### Información del bug

Navegador: Opera

Al pinchar sobre la imagen de zeling y nissaxter en https://lavelada.es/pronosticos

**Comment by AlejandroSuero** [comment]
@jBenitoLopez es sólo con esa pareja o combate, o también sucede con los demás?

Estás usando algún **adblocker**?

**Comment by AlejandroSuero** [comment]
@pjmartorell he hecho los cambios en #952, he mantenido el filtro en caso de que no sea 2v2 y si lo es, que busque en el boxeador en el `voteId`.

**Comment by jBenitoLopez** [comment]
> @jBenitoLopez es sólo con esa pareja o combate, o también sucede con los demás?
> 
> Estás usando algún **adblocker**?

si, solo es con esta pareja, los otros deja votar sin problemas. 

tambien desactive todos los addblocker que tenia y sigue pasando lo mismo, espero que sea de ayuda
