### ISSUE TITLE
[Bug]: Falta el peso del Mariana

### ISSUE THREAD

**Issue by burdas** [midudev/la-velada-web-oficial#964]
### Señala los requisitos cumplidos

- [X] Estoy corriendo la última versión.
- [X] He revisado si ya hay un issue creado con características similares.

### Comportamiento esperado

![image](https://github.com/midudev/la-velada-web-oficial/assets/36920138/fb296220-bab3-4f5c-993c-67788d29772a)
![image](https://github.com/midudev/la-velada-web-oficial/assets/36920138/bbb1d0c5-9180-46dd-9701-4a0d7dcf8ff8)

### Comportamiento actual

![image](https://github.com/midudev/la-velada-web-oficial/assets/36920138/d6885ce9-eda5-4f1a-ae8c-8688a456e425)
![image](https://github.com/midudev/la-velada-web-oficial/assets/36920138/e1818450-0f17-46b7-ad40-7b036da47c2b)

### Información del bug

Hola Midu. Creo que igual ya habéis tratado este tema en tus directos, que aun sigo viendolos. Pero veo que le falta el peso a Él Mariana y entiendo que debería estar. El peso que he indicado en las imagenes lo he cogido de internet. Desconozco si es el actual.

### ¿En qué navegadores encuentras el problema?

Chrome

### Sistema operativo

Windows

**Comment by AlejandroSuero** [comment]
@burdas gracias por darte cuenta, he subido un fix en la PR enlazada arriba.

**Comment by burdas** [comment]
Perfecto!! Muchas gracias!
